### PR TITLE
Improve article about Code Smells

### PR DESCRIPTION
**Pull request by GustavBertram**

### CODE REVIEW

**Comment by thomaskuntzz** [comment]
Hey @GustavBertram

I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

---

> If you're not familiar with the merge conflict process, feel free to look over GitHub's guide on ["Resolving a merge conflict"](https://help.github.com/articles/resolving-a-merge-conflict-on-github/). 🔍️

**Comment by GustavBertram** [comment]
Updated. Looks like someone else's edit got merged first.

**Comment by thomaskuntzz** [comment]
@GustavBertram Cool, thanks for picking this up so quickly! 👍

**Comment by thomaskuntzz** [comment]
Are you ok with the edits I made?

**Comment by GustavBertram** [comment]
@thomaskuntzz Looks good!

**Comment by thomaskuntzz** [comment]
Great, thanks for your contribution!

**Pull request merged**
