### PR TITLE
Feature/linux command prompt

### PR DESCRIPTION
**Pull request by jp-sauve**
**Description**

### CODE REVIEW

**Comment by jp-sauve** [comment]
Less complete pages:
https://github.com/freeCodeCamp/guides/pull/6178
https://github.com/freeCodeCamp/guides/pull/4959
https://github.com/freeCodeCamp/guides/pull/3463

Contains some commands this PR doesn't, but I'd argue that they're not really in the top 10.
https://github.com/freeCodeCamp/guides/pull/3054

**Comment by philliplaibe** [comment]
Thanks JP you rock!

**Comment by fvcproductions** [comment]
@jp-sauve I think there's a lot of great content here but I think the formatting could be improved to increase readability so it's easier for the reader to skim through and grasp key concepts. Right now, I feel there's a lot of content that could overwhelm the average reader and the command prompts don't feel emphasized enough.

**Comment by fvcproductions** [comment]
I made some formatting changes and think it serves as a great addition so I'm going to go ahead and merge!

**Comment by jp-sauve** [comment]
Thanks a lot! I look forward to helping build the Linux section out some more too, once the backlog is clearer.

**Pull request merged**
