### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by escottalexander**
added power supply category inside computer hardware.

### CODE REVIEW

**Comment by texas2010** [comment]
umm why did you add ide article?

**Comment by escottalexander** [comment]
Is that a bad idea?

**Comment by texas2010** [comment]
@escottalexander we already have it. i dont know why you add it. please untrack that in the git.

**Comment by escottalexander** [comment]
I’m sorry, I searched for it but didn’t see it. How do I untracked it?

**Comment by texas2010** [comment]
no....   please make new PR. but do not add ide...

**Comment by escottalexander** [comment]
So should I close this pull request and start over without my mistakes? I am truly sorry for the trouble, I am a beginner on GitHub and so any guidance would be appreciated.

**Comment by texas2010** [comment]
@escottalexander no problem. it is better to make new PR and send article you did write.   since you did write two article that is fine to me.

**Comment by escottalexander** [comment]
And to do that do I copy those commits to a new branch and then do the pull request?

**Comment by texas2010** [comment]
Yes new branch on the local. then send PR

**Comment by texas2010** [comment]
i forget to add. you can add Expansion Cards article too

**Comment by escottalexander** [comment]
Quick question, you say "local" branch. What is that called and where do I find it? Thanks.

**Comment by texas2010** [comment]
wait. which one you work on github or your computer?  I was talking about local as use your computer.

**Comment by escottalexander** [comment]
I am on GitHub website. Not using the terminal to access it.

**Comment by texas2010** [comment]
oh ok.  you need to make new branch then create folder and add article like you did.

**Comment by escottalexander** [comment]
To clarify, am I making a branch off of the freecodecamp/guides?

**Comment by texas2010** [comment]
I have no clue. I don't work on GitHub and do stuff in there. I always use git on my computer.

**Comment by texas2010** [comment]
thanks i did merge your PRs.

**Comment by escottalexander** [comment]
Thanks of the direction and patience. I really appreciate the help.

**Pull request closed without merging**
