### PR TITLE
[WIP] Add initial guide markdown files

### LINKED ISSUE #1: Chore: Import all of the existing forum guides and put them in appropriate folders and subfolders.

### PR DESCRIPTION
**Pull request by Bouncey**
closes #1

### CODE REVIEW

**Comment by kuriakinzeng** [comment]
LGTM. We just then need to link these pages up to the categories/subcategories. Need advice on the directory structure if you already have one @QuincyLarson

**Comment by Bouncey** [comment]
@QuincyLarson I think the Netlify reports are linked to your account. I am unable to view them

**Comment by Bouncey** [comment]
Don't merge, I think I have it now, just have to alter my `.md` build script

**Comment by Bouncey** [comment]
Closing this, there is a weird merge conflict

**Pull request closed without merging**
