### PR TITLE
Added Bread Crumbs to search results #206

### PR DESCRIPTION
**Pull request by dhanushuUzumaki**

### CODE REVIEW

**Comment by dhanushuUzumaki** [comment]
screen shot 2017-10-03 at 8 03 23 pm

**Comment by dhanushuUzumaki** [comment]
search freecodecamp guide

**Comment by QuincyLarson** [comment]
@dhanushuUzumaki Awesome - this looks really cool. I'm going to leave this to @Bouncey and/or @systimotic to QA since they're more familiar with the Guide platform and the performance implications of this.

**Comment by dhanushuUzumaki** [comment]
@Bouncey I didn't touch the breadcrumbs file. I will look into it. Let me close this one and create a new one.

**Pull request closed without merging**
