### PR TITLE
add info and example for articles

### PR DESCRIPTION
**Pull request by nelruk**
add iframe concept, href attribute and comment tag

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@nelruk Excellent work! Thank you for contributing these articles! Merged!

**Comment by texas2010** [comment]
oh dang. I noticed that link say https://www.freecodecamp.com.
more like it suppose to say https://www.freecodecamp.org.

**Comment by nelruk** [comment]
about your https://github.com/freeCodeCamp/guides/pull/107#issuecomment-320791295 comment @texas2010 for me it works fine the link! :)

**Comment by QuincyLarson** [comment]
@nelruk it still works (it gets redirected) but we should use freecodecamp.org going forward. No worries for now, though. We can do a global find-replace later.

**Comment by texas2010** [comment]
yeah. not a big deal.  I know we could fix it later.

**Pull request merged**
