### PR TITLE
Update ruby introduction article

### PR DESCRIPTION
**Pull request by iFalcao**
Updates ruby current stable version and references frameworks as gems

### CODE REVIEW

**Comment by Bouncey** [comment]
@iFalcao Thanks for the edit :+1: 

Whilst you have this open, could I ask you to add some formatted code blocks to this article please?

For example
` ```ruby`
```ruby
if 'welcome' == 'welcome'
  print('Hello campers!')
end
```
This will add some syntax highlighting, which we all love more than mono-colour text

**Comment by iFalcao** [comment]
Seems good @Bouncey!

**Comment by Bouncey** [comment]
@iFalcao I forgot to mention, any cli blocks can use ` ```shell`

**Comment by iFalcao** [comment]
@Bouncey does that look better? I think we shouldn't extend the installation part.

**Comment by texas2010** [comment]
dang, this file has a conflict.

**Comment by texas2010** [comment]
@Bouncey I fix some. do you want to review this again?

**Pull request merged**
