### PR TITLE
Added article for functional programming

### LINKED ISSUE #433: Article on Functional Programming
Since we mention Functional Programming in [the Medium article](https://medium.freecodecamp.org/heres-a-new-way-to-learn-coding-tools-and-concepts-right-when-you-need-them-ee82d15c576d), we should create an article on Functional Programming in case people search for it. 

Would anyone be interested in writing it? It could go in the Software Engineering folder.

### PR DESCRIPTION
**Pull request by chiragbhansali**
Closes #433

### CODE REVIEW

**Comment by danedavid** [comment]
LGTM

**Comment by HKuz** [comment]
Awesome write-up on functional programming, @chiragbhansali - thanks for getting this out so quickly 😄  This LGTM!  🎼 🎸 🎶

**Comment by QuincyLarson** [comment]
@chiragbhansali Awesome! Thank you for doing this so quickly. I enjoyed reading your write-up! I still think there is room to simplify it. For example, most newcomers don't understand "declarative" versus "imperitive" so you could put in parenthesis something like this:

> declarative (telling the computer what you want to do) instead of imperative (telling the computer exactly how to do that).

**Comment by chiragbhansali** [comment]
@QuincyLarson Thanks:smiley:. I made the changes and created a new pull request. #505

**Pull request merged**
