### PR TITLE
Additions To Text

### PR DESCRIPTION
**Pull request by Aditya-Sood**
Made additions to the existing text for a more wholesome read. The reader should have a good picture of the topic after the read, and an idea of where to go next.

### CODE REVIEW

**Comment by nsuchy** [comment]
Hey @Aditya-Sood

So I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

---

> If you're not familiar with the merge conflict process, feel free to look over GitHub's guide on ["Resolving a merge conflict"](https://help.github.com/articles/resolving-a-merge-conflict-on-github/). 🔍️
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝

**Comment by Aditya-Sood** [comment]
Hi @nsuchy 
I've resolved the merge conflict
Have a look
And thanks for the heads-up - I wasn't aware that there was one

**Comment by Aditya-Sood** [comment]
My bad

**Comment by Aditya-Sood** [comment]
Thanks for merging

**Pull request merged**
