### PR TITLE
Fix/object prototype hasownproperty

### PR DESCRIPTION
**Pull request by Marmiz**
Following up #122:

1: modified object/object-prototype-hasownproperty instead of adding an entire new article.
(sorry for missing it the first time)

2: removed the reverence to `npm run meta` from README.md.
Now it should read:
>Write your article, commit your changes locally, and push your new branch to GitHub with the command `git push origin <new-branch-name>`

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@Marmiz This looks solid. @Bouncey is it correct that we no longer need contributors to run the `npm run meta` command?

**Comment by Bouncey** [comment]
@Marmiz @QuincyLarson the change to the README file is required, and I opened an issue (#136) earlier for it to happen. #137 has been raised to close the issue and remove the reference to the meta script. 

I didn't realise this PR edits the README also

**Comment by Marmiz** [comment]
Yet again I caused more harm than help, I'm so sorry.

I was following the little conversation we had in chat @Bouncey, and fixed the README while I was at it; without really looking if an issue  was been created.

We can close this one, and I can go ahead and submit a third PR; this time I promise I'll stay in my boundaries and just update the stub.

Sorry again for the mess :)

**Comment by Bouncey** [comment]
@Marmiz don't worry about it. No :octocat:'s  were harmed in the making of this PR!

I didn't see a response from you in gitter or an issue raised here, so I raised it myself.

We appreciate any and all help offered in making this project a success.

These changes look good to me 👍 

Thanks @Marmiz  ✨

**Pull request merged**
