### PR TITLE
Added link to another excellent resource for API

### PR DESCRIPTION
**Pull request by akshay1337**
Provided link to a great Medium articles by Petr Gazarov from freeCodeCamp's Medium publication.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit 124827da180990d4b72460c8fdcdb546432266a7

https://deploy-preview-3244--guide.netlify.com

**Comment by ChaituVR** [comment]
Thanks for the PR! :+1:

**Comment by akshay1337** [comment]
My pleasure. Thanks for the merge.

**Comment by ChaituVR** [comment]
Keep them coming :smile:

**Comment by akshay1337** [comment]
I will, probably in the Deep Learning guide.

**Pull request merged**
