### PR TITLE
Fix build errors caused by frontmatter problems

### PR DESCRIPTION
**Pull request by systimotic**
_Another day, another broken build!_ 😂
_Yesterday, you got a free error, today you get three for the price of one!_

Three new issues that prevented the build from working. We should probably create some strict linting for the articles and add it to the CI to prevent things like this from happening so often.

/cc @Bouncey

### CODE REVIEW

**Comment by Bouncey** [comment]
@BerkeleyTrue Re: our conversation on Skype.

**Comment by Bouncey** [comment]
Netfliy has a deploy preview bot that we are currently not using. The bot builds the PR and lets us know if it succeeds or fails, with a preview of the site on success.

We are trying to address this

**Comment by Bouncey** [comment]
@texas2010 @HKuz @dhcodes @erictleung 

Please be aware that all articles need

```yml
---
title: Article Title for the UI
---
```

**Comment by systimotic** [comment]
That would be really useful. I feel like I recall seeing that used here before, but it was removed, no?

**Comment by Bouncey** [comment]
In the beginning yes, but I can't remember the reason it was taken away.

**Comment by dhcodes** [comment]
Hmm. I think I just merged one last night where that was removed. I will unmerge, make the edit, and remerge.

**Pull request merged**
