### PR TITLE
Move the Ruby Introduction article to Ruby index page

### PR DESCRIPTION
**Pull request by iFalcao**
In other sections, e.g Python, there isn't an introduction page because the section's first page already serves as an introduction. In Ruby section, the Introduction page was causing a redundancy with the first page, therefore I moved it to fix.

### CODE REVIEW

**Comment by texas2010** [comment]
@iFalcao this PR have a conflict.

**Comment by iFalcao** [comment]
@texas2010 That's because I'm trying to move the ruby-introduction article to the index of the ruby section. As I said in the description of the pull request above, I'm trying to follow the pattern of other sections, such as Python i.e.

**Comment by texas2010** [comment]
yeah that is fine but i am not sure why src/pages/ruby/ruby-introduction/index.md have a conflicts.  since you plan to delete a file of that.  odd

**Comment by iFalcao** [comment]
@texas2010 I think it's because I'm deleting it

**Comment by Bouncey** [comment]
Is this edit still required?

Can the conflicts be resolved?

**Comment by iFalcao** [comment]
@Bouncey isn't it supposed to raise conflicts since we are deleting a file + folder? I can't understand the conflict on ruby/index.md though

**Comment by erictleung** [comment]
@iFalcao the conflicts are because the `index.md` file has been modified since you made your PR (https://github.com/freeCodeCamp/guides/blob/master/src/pages/ruby/index.md). Please update your branch so you can resolve these conflicts. Let us know in the Contributors room (https://gitter.im/FreeCodeCamp/Contributors) if you have questions.

**Comment by iFalcao** [comment]
Thanks, @erictleung. Your comment was really helpful, I hope the merge conflicts will be solved now.

**Comment by iFalcao** [comment]
@Bouncey and @texas2010, the conflicts were resolved!

**Comment by Bouncey** [comment]
Thanks for sticking with this @iFalcao  👍

**Comment by Bouncey** [comment]
Oooops, wrong button!!

**Comment by iFalcao** [comment]
@Bouncey apparently this still have an error. Could you help me find out what is happening?

**Comment by iFalcao** [comment]
@Bouncey Seems like it's gone. Thank you for the merge!

**Pull request merged**
