### PR TITLE
Add about Linked List to article

### PR DESCRIPTION
**Pull request by AmaluSusan**

### CODE REVIEW

**Comment by texas2010** [comment]
Please read this [style guide](https://github.com/freeCodeCamp/guides#article-style-guide).

**Comment by brian1999lin** [comment]
Is copying and pasting from sources allowed?

https://en.wikipedia.org/wiki/Linked_list

@texas2010

**Comment by texas2010** [comment]
oh well, I have to close this PR since you delete your fork repo. so I guess I cant ask you fix it. sorry

**Comment by brian1999lin** [comment]
It needs a source in the future... shouldn't copy and paste.

https://en.wikipedia.org/wiki/Linked_list

@texas2010

**Comment by texas2010** [comment]
@brian1999lin we are not worried about that now because if I merge this without fix something. guide repo will have a problem..  but she deletes fork repo. that is why I closed it.

**Comment by brian1999lin** [comment]
@texas2010 Yep, just wondering about future practice since I read the Code of Conduct and didn't see anything for plagiarism. Thanks!

**Comment by texas2010** [comment]
yeah no problem.

**Pull request closed without merging**
