### PR TITLE
Index.me

### PR DESCRIPTION
**Pull request by cwesta**
Visual Basic for Applications is the programming language created by Microsoft for use within in their applications; Office, Word, Excel, and Access. It is an event-driven language and can be used to build user-defined-functions(UDFs), access windows API, automation(OLE), and dynamic-link-library's(DLLs). However VBA is not a standalone language and cannot be used outside of a Microsoft application. VBA has many uses, in the office space it is often used to automate tasks and generate reports. Since it is a easy language to grasp it is user-friendly and easy to implement into almost any office task.

### CODE REVIEW

**Comment by cwesta** [comment]
Need to change index.me to Index.md

**Comment by texas2010** [comment]
Thank you for your pull request. Please read this [style guide](https://github.com/freeCodeCamp/guides#article-style-guide). I am closing this pull request for now. Please let me know if you have any questions.

**Comment by cwesta** [comment]
I read the style guide and changed the outline. I clicked commit but I can't find it after that what did I do wrong?

**Comment by texas2010** [comment]
i closed this because there is nothing in the file.   at first you need to create folder then create index.md

**Pull request closed without merging**
