### PR TITLE
Created an overview on each operator

### PR DESCRIPTION
**Pull request by derek-cook**

### CODE REVIEW

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f41.google.com ([209.85.218.41]:50145)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5JcT-001Zv0-Ts
	for pawan@oss-india.net; Fri, 20 Oct 2017 04:19:12 +0530
Received: by mail-oi0-f41.google.com with SMTP id w197so17450921oif.6
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 15:48:33 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=ymykkVfdqvQgPNz/c9TWsUoEB2BCjOlQPkTBfyG0qQE=;
        b=Frv22ymrsgbtNfMJ+d4PKI7tMxwdSVrtC8JwRW9Rh9A4TAqrQV/ZKXUcMK02R35TKt
         evbb5OkaI9zikRsl4mFqBqvhZ1dqZ9uit6QSUFfpC3hWBZtOync2yEl4419PheA+gitI
         K8Ue32K7V78vNddX7kOcVFZz4EmUY2j79bYiA/XM1exZ4+nLi/7va9skv0QIeQpVfrNN
         BiogVCB8JGKlS5/QK+fAspJ4RDktAVgehCvzDBnxQZXmQvd1C+pdPVI0pnnTwnZOWe67
         ibuEQv8EdJUs+IhtTz+DX21125DGYHtOroJS55YtE2vutUAgv1CV6dEN18H/PGBeDc4n
         6vjA==
X-Gm-Message-State: AMCzsaXfPQqCHbqLWgyuH6YMkEYC8SlDDGKQrRNCqvUwn5j/eyqXuFd+
	9xZbfbLtOlibMlGFY0BFUC1PHawwSEIEaRJq/6ulI/jOL/umneY=
X-Received: by 10.157.83.37 with SMTP id g37mr2072398oth.437.1508453291196;
        Thu, 19 Oct 2017 15:48:11 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4399793ofa;
        Thu, 19 Oct 2017 15:48:10 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+TelpezUTPvCIA1QoC2NWjtwYO0unAH2xSrjf30vkfYRFdXcCPAghzq+4U+Z/N3m5e2esra
X-Received: by 10.107.53.42 with SMTP id c42mr4151124ioa.254.1508453290549;
        Thu, 19 Oct 2017 15:48:10 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508453290; cv=none;
        d=google.com; s=arc-20160816;
        b=lbR98WgA23Eru0AbfsASl/KicvPI8y9UNOC7P2yrkhxwzyu719qG0xUOuiWSOdvq+d
         VxLSyQEGzoGG8FWh5ABZTwVhXLbBOi9M67uMZ/U1Y5bgbRxUSG+vHlSWxcg86g3bvBS6
         0YnweVTd5AsafbwU6PIWA9+rd6dQEBxaQC3+nl2ASnHBAYSN3anpP4y1SfhWQDyTX6JX
         RJ6y54uWqoRcUYY4Uf4O/Qxv1fbvoaovGl46tG0wgU8kG42TKCIaciHcULrgsMthA7Pl
         fZ+PWzl6PUYu9sZHDh1tjbu1RSnMoNS7pTEC4NjUT5/iqGQaUbyaeWfB2B5nMwhGjtHj
         8A/Q==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:message-id:cc:to
         :reply-to:from:date:dkim-signature:dkim-signature
         :arc-authentication-results;
        bh=ymykkVfdqvQgPNz/c9TWsUoEB2BCjOlQPkTBfyG0qQE=;
        b=lT1Uejw3rBuughhEf0lI6Oto4+QbJgk/hGNUe2D97tYuZSEllcq/qEz/tk23Wvt3iM
         zyl2xrDAP/jUd7l23B6bkmYQbgwcNxb7brhjISm7mLHTdS95zY+Ssq8AZVGEm20MKY+Q
         ki+nlJL8gjZrWsK6ZlvQEKOeuQRpcOnA3isgS++d9+6QViLPzngr+CmO/KMjvui5dYfn
         fff/NpCRJyepP8tLcoflBynWHBHq+tFTdDqtptGiieFre1MLogAl0AJDrzugxR8wCahL
         ZE6lf6kLtjqYbIjOYMLAYHgePkgNUN52EN95ymEHL6CiWDnnUfey1CXjMSU5+p5ZAe2j
         gonw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=hjMNBPCg;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=wcAhCs0l;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o3.sgmail.github.com (o3.sgmail.github.com. [192.254.112.98])
        by mx.google.com with ESMTPS id e1si2125403ite.142.2017.10.19.15.48.10
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 15:48:10 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) client-ip=192.254.112.98;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=hjMNBPCg;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=wcAhCs0l;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=1Z/6n3aFV09WNKdLIoHojxeLxEE=; b=hjMNBPCg3e+XNSvI
	qzdNqhnObz8kSaDsBrCjt1ywuVaC9ZrRuooDRMg4sA+bDl6hFK7nfq/ISCskiU21
	yJDoJGEIOX8dsclM1gxOj+zmp2u03OQNkdemADqTRuGmGWP4fHdmNZE12pAyWTHT
	bLGML2tBedf3B+RlLepvI6R8wcs=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=1Z/6n3aFV09WNKdLIoHojxeLxEE=; b=wcAhCs0lK8Qq8Ef1NY
	ziff3YgnQcVidElG1EZJO7REaaUEiKtgv9yRqvU9UjgiEyrFMawh6QNgqBC2SM4q
	0oQtpWLktf7Dr92mnwR9YfHiN0jh0Zv8108rNo5PYbcVOXNHaS3mmRmDhOVqsI4W
	TYdP1qw4mmudGNlpwk6Qii9es=
Received: by filter0514p1mdw1.sendgrid.net with SMTP id filter0514p1mdw1-26646-59E92BA9-8
        2017-10-19 22:48:09.109491317 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0010p1iad1.sendgrid.net (SG) with ESMTP id ISUSmISeSZqgYlxGprbRLg
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 22:48:09.068 +0000 (UTC)
Date: Thu, 19 Oct 2017 22:48:09 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (116/100 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f44.google.com ([209.85.218.44]:50893)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5Jec-001aQj-DG
	for pawan@oss-india.net; Fri, 20 Oct 2017 04:21:18 +0530
Received: by mail-oi0-f44.google.com with SMTP id q4so17448929oic.7
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 15:50:45 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=IAAUBMiJOWNPsSggtS9qXcVlT3r9OB7nnKu3EXcbJ0c=;
        b=EBE12fUGDZpCNrvGpJbWHi6qZe2+TFkzJTOZa9pZnjndgBhhVOn7l7lNzpXkzSWya+
         /oyEbmxEZ9UnVtzGR9LQ7i7I+KNJRdbc+P6R8xlrtXSPVSy3V8H2IJyJXHkx9Y/sU3mz
         /Dl+mlni+JX8ZZxQ6HlhL0GA7uRY4r2IqaFs6LVydJO+8n491MhBv7HV9gVf1nXsy6Ev
         2ni8Q5LFOZ9QaAR5eWiYp9r6/y/IyivFfFtDUbVHfL/c7shPN2BU5RZrVi5jQ7UAi5SU
         SWcYUSM1EcNa23V0V9iDDZCvayoU8cd55wNWPRgN3ADOzDPTxQagkxMGKfYb2G7uXQmZ
         Mr6Q==
X-Gm-Message-State: AMCzsaWQR/CoYhE7BQfZCYElY6yyFyL/yh3J2UIYfeEVSF+QZ5z7S3ba
	tF7buHFb7Y/7QzXua6jxZd2mR3Ib45k+P+1sK8ZsbQ3h8ksrZL0=
X-Received: by 10.84.77.6 with SMTP id v6mr1568441oix.347.1508453423533;
        Thu, 19 Oct 2017 15:50:23 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4401510ofa;
        Thu, 19 Oct 2017 15:50:22 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+QMbOdjLkElLpdhYpvjxwslMQwIXlEQGrd3qC7jO/FkRm0QLHhAevzc+N3D2R73wQaTJZsM
X-Received: by 10.237.55.66 with SMTP id i60mr4314696qtb.176.1508453422813;
        Thu, 19 Oct 2017 15:50:22 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508453422; cv=none;
        d=google.com; s=arc-20160816;
        b=DEp814B+ocWS3FYKy8FeB/2OA18X9GbVQpMb/OS4qV1nY8JtUOnuoODSmWPJoMwsMI
         I7aWfW9pHGcMLjD70DuCeApc5j7ORsaKtRsiU3Rg6qmEBdT9HIUU5M1mFOpuHEB4tITL
         8BnRFQdR7cETAMg2H507Fa2Xva2Yl+L3M1adZ1xUx96Zemv4kOaYLIy2WMGZJtaal8XR
         J+9lIms0SZ0dx0JxO0qA2pFRORgvxlY/g2hORyiR1lbzjqsHL9kVWjX9XKWQ/U3PVJzz
         unG3uY13J15arDs6i9YGuyH0OvvcIC6culnL79qicYY0OKy3Y8j8VqS+gee4Pqm1eXgS
         jqwA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=IAAUBMiJOWNPsSggtS9qXcVlT3r9OB7nnKu3EXcbJ0c=;
        b=HFxYzE8CeutANTQ564MdYwqKaFY9jtW2sZEzHWd+gKrOcSAChYAlt1JyJ1USerflXK
         NJ3LwU1w6EBn55Snxh/TArLV3y42T2TjQ1nk2TxaUIiGzkqOZOhgsi+sLb2vFRkAYV6I
         9XMwH4IJtMMFLO5DRDs6dFVvzQdxg0FjpfnrdX7pY3jrfAlU0Gsz8QJ1WKNwgG6TF1St
         nEVolIo2mpbpQDjxcq5QepPqMfPlDffGCRosUyEWcxTUnpZ9KqyXbIz135cPNWlhZosg
         3yX+2xQpCM8ZoCz5lgqQZnmumKntQLZhcjkRqV5m06i6aYXFVNlwOlu0hWcl7PA3jzAh
         sxcw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=q6Na1Se+;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=IrOwJius;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.10 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o5.sgmail.github.com (o5.sgmail.github.com. [192.254.113.10])
        by mx.google.com with ESMTPS id 51si5811402qtt.476.2017.10.19.15.50.22
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 15:50:22 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.10 as permitted sender) client-ip=192.254.113.10;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=q6Na1Se+;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=IrOwJius;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.10 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=7OU7lW0JT87XkGdYpgwwnZGzoAY=; b=q6Na1Se+jhiyv/7l
	+JiHsZjOPmSJPLvwpQLbIWToeDwHfYJGeuCerzdkb5UnwKYu0URfBtzY1jTdcz6g
	IQ63tjcDXG+Vo4rH1ABr+C3ITX5oq1xqtsFJ9B+insmZrKdwF2fFBsYhGR1BhqTk
	FE5UuvVwgNqKnHAnzfsrrrTibRE=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=7OU7lW0JT87XkGdYpgwwnZGzoAY=; b=IrOwJiusG5zSU51c4m
	2P5GNn6d85lgxS7hYt9XujI+UCcWVz58u1YpuOcm1FZ9inzQRQwgNW78TPSQI14p
	545lS/rUQwWFAUkqGGwoCA42WnmZg5VvRo4J1hloH4eaonUoEw8TYbGxZP/DUIwx
	ohGPz/6OCnEVMZ47gA45bWIyw=
Received: by filter0133p1iad2.sendgrid.net with SMTP id filter0133p1iad2-1086-59E92C2E-1A
        2017-10-19 22:50:22.39130758 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad2.sendgrid.net (SG) with ESMTP id objf6axoTNuVKtwiazmf0g
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 22:50:22.414 +0000 (UTC)
Date: Thu, 19 Oct 2017 22:50:22 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f41.google.com ([209.85.218.41]:45669)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5Jef-001aSm-Rv
	for pawan@oss-india.net; Fri, 20 Oct 2017 04:21:21 +0530
Received: by mail-oi0-f41.google.com with SMTP id f66so17476968oib.2
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 15:50:48 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=i40ABVWr4HXjaCQq73NXGArwQv6uwh9Ae1mDjKfoMzk=;
        b=tddpqyo02PC3PPXnNZz69/JkNndaOP60HBXgME0Wwu/ZrAw4s0OfgP3/ZLhd/91v75
         evIAKrGLJqC0iu69VnqwW9W/U+q1VLu1JY0V6bCd3fCDVcU3pW7F7fQIzv6ybkkBIeM3
         DKELaGBsL2/FOzE2Qp4wYVwcnkD9qt1zBeGkViJ3vbQ6DjCY5TIoipKzALejsyYSTf61
         KsmrBS3lulSMj+vbF1BGMifcrXokRDtYSNuAKjhu0tWouRTNnmsKxPLUyea8e+YhBb56
         yMyZuOsP36Nmykt4ZPoN2Ke8kbIsk8kikh/LLQTNq68gxae903sR0YEYkZCavr9VaA/m
         0wtQ==
X-Gm-Message-State: AMCzsaVLCBgJaUBAnfD9LXGivuWv81GKiXK6G12XRA/NKnqfsK+xXKOS
	glj/YoO2zwUk2t0isQR398qrCOxfE7CgwowSqiYuE1A5YQWBCz4=
X-Received: by 10.202.245.197 with SMTP id t188mr1598270oih.354.1508453426933;
        Thu, 19 Oct 2017 15:50:26 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4401568ofa;
        Thu, 19 Oct 2017 15:50:26 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+RJ1HYY6n225K/4oXURWb72kkie+Iw18eAkGuHcjHWrm062YZtrhQ2cuZF35AOK4O86Pl7i
X-Received: by 10.107.27.144 with SMTP id b138mr4330577iob.9.1508453426177;
        Thu, 19 Oct 2017 15:50:26 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508453426; cv=none;
        d=google.com; s=arc-20160816;
        b=YsB88NnMtIKGRmhMOcEdu07WkNmRZfEiGAZiAiaTEJcOGL/tg4UjhNwf4wvxEseGf3
         cNtfgic318Xdb5Y7Z2awJH/3ftYqQY2ec9peMQw9haw000AD/5XmLorOrQ0nMdwRr64y
         tyFC7uY/s48UF94tjBX0I9Wod3pwOCoK2babIRLSlmv4DXuM2oLkTDYzhLg6xI+JEWK2
         hu7/sLOCccNIM6EONDk8blrZ92KNAOfaTClwgC+fyOEV2l97nnUW5NhgxE0jlQwV5fL8
         r8kLwt/a6BlyPecLN0pZh4gaZBTREbRmzQTfyc17rmoZkZhHziC7jCzlN429ycUOeYoB
         rFKA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=i40ABVWr4HXjaCQq73NXGArwQv6uwh9Ae1mDjKfoMzk=;
        b=A0kTHFmbDitztz/urUxz0LlHFVqi5XLgbyTs00qZ9e4CMUJagI4/iC+H8RbypG2xez
         GWV6eyKsvs0XxEy9PK4B+186CkFY5GcndM8RLJ7DXv9HkUCxPMQOoGa5DiBk914qHoxP
         IPjhZ/8HOksfGz2TMeSIln0nIPt5Ju3Arl829KCet2mXA+qVKewvo+58ejxD8a2NKlA1
         Sif5Xw/QYP2RXokHaov+8tc4cZVAuWu7xg4q+J93WKiVfyS6oUUhTehxI57s50aIgW2K
         eGPytTQbTBfhWYLdA9QGXOo9eqB+VVlpku/KIPkfltSM2DRfC71sYUajyIva/noWVaa4
         tpfA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=BrlAhu7p;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=LGOrXPuB;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o3.sgmail.github.com (o3.sgmail.github.com. [192.254.112.98])
        by mx.google.com with ESMTPS id m79si2155631itm.43.2017.10.19.15.50.26
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 15:50:26 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) client-ip=192.254.112.98;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=BrlAhu7p;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=LGOrXPuB;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=dRKHAY50cEN7vAiZk/Bo5R/Lmd4=; b=BrlAhu7pfUfr5u+b
	nDeAWcbMLZ9PGya0eBHktTK7WZjlFLFj12fh7MEu6P6gU2zIVj1etFHN9MACHR99
	lxD7sNkBa1IPnMhzU8uwVCwwis28UjAJqkMRB7pCvn96HNbG60VuGKQyR0Ly7NnV
	0gzHyh/DpF5WDYLHvKFrPGQZCPQ=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=dRKHAY50cEN7vAiZk/Bo5R/Lmd4=; b=LGOrXPuBsM9796P6KR
	DLBo/RIv/iDo1cS7e9A8uN6MtioZgp8ECoJjAk+Mo1kiwxH02BIcc6ycB20c4ljp
	LAqwSaAs4s3lO2kLbq9E9uX1IyfCaj65OMxYQ8PD2Ml97JVBKnZPmxI5VJrTcdPs
	BssejCmai+Ollcq19Zwvx+s7Y=
Received: by filter1138p1mdw1.sendgrid.net with SMTP id filter1138p1mdw1-2600-59E92C31-15
        2017-10-19 22:50:25.930494348 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0010p1iad1.sendgrid.net (SG) with ESMTP id XSJyecklRgSltHmmUZowTg
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 22:50:25.904 +0000 (UTC)
Date: Thu, 19 Oct 2017 22:50:25 +0000 (UTC)

**Comment by jp-sauve** [comment]
We apologize for the inconvenience, however, while your PR was in the review queue someone else proposed changes to the same file and we merged their contribution. As a result, there were substantial merge conflicts that we were unable to resolve. We will be closing this PR for now, but you are welcome to try to resolve the conflicts yourself and reopen the PR. If you're unsure about this process, feel free to reach out in the Contributor Gitter channel or comment below. If you decide to resolve conflicts, we recommend you review the existing file to figure out how you could incorporate your own ideas while maintaining the other contributor's work. 
I also recommend that a rework include logical operators as they relate to programming languages. One example is "&&" for AND, used in C, JavaScript, PHP, Java.
Thank you for contributing and keep up the awesome work!

**Pull request closed without merging**
