### PR TITLE
Create ruby-hashes

### PR DESCRIPTION
**Pull request by ryandav**

### CODE REVIEW

**Comment by fvcproductions** [comment]
Hey @ryandav 

So I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

---

> If you're not familiar with the merge conflict process, feel free to look over GitHub's guide on ["Resolving a merge conflict"](https://help.github.com/articles/resolving-a-merge-conflict-on-github/). 🔍️
> 
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝

**Comment by ryandav** [comment]
This was a new file that I thought would be good to add to the folder - I don't think this conflicts with anything already on there...

**Comment by ryandav** [comment]
https://github.com/freeCodeCamp/guides/pull/7812
I see that there was another file in a different path on ruby-hashes. I've added to that instead.

**Comment by fvcproductions** [comment]
@ryandav It seems that similar changes have already been accepted earlier for this article you're editing, sorry about that. 😓

If you feel you have more to add, please feel free to open up a new PR. 

Thanks again! 😊

**Pull request closed without merging**
