### PR TITLE
JavaScript - Comparison and Logical Operators: added my content

### PR DESCRIPTION
**Pull request by nicholasnbg**

### CODE REVIEW

**Comment by texas2010** [comment]
this file has conflict.

**Comment by nicholasnbg** [comment]
Hi Texas2010, I'm new to contributing on GH, and am not sure what exactly is conflicting in the file? Can you  help me understand what's gone wrong here, I'd like to keep contributing to FCC guide.

**Comment by johnkennedy9147** [comment]
@nicholasnbg Hi, the stub you edited has already been changed by another pull request and your version conflicts with the current version.  There was a stub for "comparison and logical operators" and an article for "comparison operators". So the stub was deleted and replaced by one called "logical operators".  I would suggest closing this pull request and copying just your content for logical operators into that stub. thanks

**Comment by nicholasnbg** [comment]
Ah ok thanks for clearing that up @johnkennedy9147 , will do.

**Comment by HKuz** [comment]
Hi @nicholasnbg - I'm catching up on this thread, and see you've since opened PR #682 that no longer has any conflicts, so I'm going to close this one. One of us should get to reviewing that one soon! 😄

**Pull request closed without merging**
