### PR TITLE
feat(license): Add CC-BY-SA-4.0 License

### PR DESCRIPTION
**Pull request by raisedadead**
Add some license goodies.

### CODE REVIEW

**Comment by Bouncey** [comment]
@QuincyLarson is this the correct licence?

**Comment by raisedadead** [comment]
This would be for the content and maybe we can add a dual license for the software, as BSD-3. But this should be the one the GitHub shows in the tab because of the primary content of the repo.

**Comment by Bouncey** [comment]
Ah, the content is going to be hosted in a different repo that is linked to [Netlify CMS](https://www.netlifycms.org/). The content repo does not exist yet though.

A BSD-3 for this repo would be great though. :+1:

**Comment by QuincyLarson** [comment]
@raisedadead we're going to store the code for the guide in this repo, and the guide articles themselves in https://github.com/freeCodeCamp/guide-articles/ so that would be the repo where we'd want to use the CC license. In this repo, we'd use the BSD-3 license.

**Pull request closed without merging**
