### PR TITLE
Add a stub for python list comprehensions

### PR DESCRIPTION
**Pull request by hayleycd**
I have found these to be really useful, but as a fresh engineer had not seen them when I first started my job.

### CODE REVIEW

**Comment by texas2010** [comment]
@hayleycd do you plan to write about that?  or not. I will close this. because write article is better more than nothing of the stub.

**Comment by hayleycd** [comment]
@texas2010 I would like to. I thought the procedure was to do a stub first (to get the topic approved) and then write the article. But if the topic looks good to you, I can write it as part of this pull request.

**Comment by texas2010** [comment]
you don't need to get approved for that.   if you want to write about that. please do!

**Comment by QuincyLarson** [comment]
@hayleycd Awesome - thanks for your contribution. Congrats on your first accepted pull request!

**Comment by hayleycd** [comment]
@QuincyLarson thanks!

**Pull request merged**
