### PR TITLE
Added support bullet for built-in macro support

### PR DESCRIPTION
**Pull request by jcastle13**
Added a bullet for VIM feature which supports macros for automative text manipulation.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@jcastle13 Thanks - this is a nice addition. Congrats on your first Pull Request!

**Comment by jcastle13** [comment]
Thanks Quincy.  I hope to be able to continue contributing even though my knowledge isn’t much in web design but in hardware design.

**Comment by QuincyLarson** [comment]
@jcastle13 Would you be interested in writing about hardware design? I can imagine a lot of developers would be interested in that, too, and would benefit from your expertise. 

Feel free to create new topics on the guide and write about them :)

**Comment by jcastle13** [comment]
I would be interested.  Not sure where to begin or what exactly I should write about.

**Comment by QuincyLarson** [comment]
@jcastle13 I recommend creating a list of hardware concepts and tools, then making sublists of specific skills those concepts and tools involve. Then you'll have a list of articles you (or other contributors) can write. Then you can commit those new directories and their stubs.

**Pull request merged**
