### PR TITLE
Regex: corrected regex in utils/regEx.js

### PR DESCRIPTION
**Pull request by chotuaashiq**
#7884 
I Corrected the regex expression in utils/regEx.js as was suggested.
@systimotic please review

### CODE REVIEW

**Comment by RohanGurjar** [comment]
@systimotic @chotuaashiq 
Just a thought on the regex in discussion.
The regex  `/^---\s*title:([^\n]*)\n---$/m`  will match the title https://regexr.com/3h8s7 as well (new lines after ---).
Hence, should we remove the * after \s and make the regex  `/^---\stitle:([^\n]*)\n---$/m`  instead, so that it exactly matches https://regexr.com/3h8sa ?

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit d912f87ef1d38673283a164aa50fce58a38460da

https://deploy-preview-7886--guide.netlify.com

**Comment by systimotic** [comment]
Good point @RohanGurjar! Do you want to submit a PR to change that `\s*` to a `\n`?

**Comment by RohanGurjar** [comment]
@systimotic Yes, would love to submit a PR! Thank you

**Comment by systimotic** [comment]
@RohanGurjar Awesome! Please @mention in the PR description once you have created it 🙂 If you need help, you can find me in the contributors chat room: https://gitter.im/FreeCodeCamp/Contributors

**Pull request merged**
