### PR TITLE
NavItem focus

### PR DESCRIPTION
**Pull request by svinkle**
## What does this do?
This PR add a new feature where `NavItem`s shift focus to the `<Article />` on click. This will help keyboard-only and screen reader users to get from the side nav to the article area quickly.

## Change log
- Updates `<Article />` to use a `class` in order to take advantage of the `componentDidMount()` lifecycle method.
- Adds `data-navitem` attribute to each `NavItem` link.
- Adds conditional to `componentDidMount()` to check if `document.activeElement` is a `NavItem` and if `true`, shift focus to the `article` element.
- Changes `div` to `article` element with appropriate attributes.
- Adjusts styling for `article` focus state.

## Screens
Everything should look and behave the exact same for sighted mouse users. 

svinkle-nav-focus

## Related issues

Related to #897.

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
Any reason this hasn't been merged yet? LGTM @Bouncey

**Comment by BerkeleyTrue** [comment]
Deploy preview failed.

Built with commit af8a1b0b7075097da51ab8d385a2173f47b89016

https://app.netlify.com/sites/guide/deploys/5a2fbaeca1147775140b735e

**Comment by Bouncey** [comment]
@svinkle Sorry for the delay, This PR was on my list, but I have no idea where the list has gone. I have resolved some merge conflicts and I am just waiting on the CI/CD to pass and it will be merged and live directly

Thank you for your patience :+1:

**Comment by Bouncey** [comment]
Thanks @svinkle :+1:

**Pull request merged**
