### PR TITLE
Added jquery and bootstrap's javascript

### PR DESCRIPTION
**Pull request by nsuchy**
This pull request adds jquery and bootstrap's javascript. This change is needed for pages that show examples utilizing jquery and bootstrap. Without adding jquery and bootstrap's javascript showing examples in action is not a possibility.

### CODE REVIEW

**Comment by Bouncey** [comment]
@nsuchy thanks for the pull request.

I will need to investigate further to see if there will be any conflicts between these libraries and react/react-bootstrap.

We use `react-bootstrap` for our UI, and it accomplishes all aspects of `bootstrap.js` without `jQuery`. I understand the need for these libs to correctly show working examples.

@BerkeleyTrue Did you manage to integrate these into the challenge framework without conflict?

**Comment by BerkeleyTrue** [comment]
@Bouncey on fcc, challenges are run in their own isolated iframe.  A challenge that requires jquery or bootstrap imports it into the iframe itself. This means it does not have a change to interfere with the rest of the site.

**Comment by Bouncey** [comment]
I'll have to have a think about it.

**Comment by nsuchy** [comment]
@Bouncey I'm not sure if it's out of scope or even a possibility but maybe we could add an "imports" feature to the markdown parser so if a certain library is needed it'll be imported just for that one page. Thoughts?

**Comment by nsuchy** [comment]
Closed in favor of #274

**Pull request closed without merging**
