### PR TITLE
Create Kali linux.md issue #7978

### PR DESCRIPTION
**Pull request by prankshaw**
Kali linux article added

Replace this sentence with a brief description of the awesome changes your PR has. 😊

---

## ✅️ By submitting this PR, I have verified the following

- [] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by prankshaw** [comment]
Please tell me if any changes are required , otherwise I can close it down

**Comment by nsuchy** [comment]
Hi @prankshaw first thanks for contributing, there is an issue though the stub has to be inside a folder with the name you want and named index.md, after you make these changes I'd be happy to merge :)

**Review by amandeepmittal — CHANGES_REQUESTED** [review]
Hi @prankshaw! Please make changes that @nsuchy suggested.

**Review by LakshitF — APPROVED** [review]

**Comment by nsuchy** [comment]
Hi @amandeepmittal I’m away from keyboard at the moment. Another user “approved” changes but I don’t see any new commits. I’m on mobile away from office at the moment. Can you read over any changes and give your opinion? Thanks - Nathaniel

**Comment by nsuchy** [comment]
There have been no new commits for a month so I’m marking this pull request as stale and will close this in 14 days if there is no response from the contributor per project guidelines.

**Comment by prankshaw** [comment]
@nsuchy I will do the required changes after this week, if that's ok.

**Comment by nsuchy** [comment]
@prankshaw That's fine - we have to close pull requests with requested changes and no activity - they're considered abandoned. As always, if a request is closed due to inactivity, feel free to contact us and we'll open it again on request. Have a fun weekend :smile:

**Comment by joshalling** [comment]
I am closing this as the requested changes were not made. @prankshaw Please don't hesitate to make the changes and submit another PR if you want to contribute.

**Pull request closed without merging**
