### PR TITLE
Bootstrap Modals: Added my changes for Modals

### PR DESCRIPTION
**Pull request by srawat19**
Added article for Bootstrap Modal with code example and explaination

### CODE REVIEW

**Comment by srawat19** [comment]
I have updated the link for 3.3.7 doc as requested.I have kept 4.0 link for additional details , in case someone feels like exploring it.
However, both the versions use the same syntax for creating Modals.

Please review  now and let me know if any concerns.

**Comment by texas2010** [comment]
Thanks! I will review it later. this will be on my todo list.  I did look it. it is good.

**Comment by srawat19** [comment]
Thank You..

**Comment by texas2010** [comment]
I close and reopen this for trigger Travis ci check on this PR.

**Comment by texas2010** [comment]
Done. I merged it!

**Comment by srawat19** [comment]
Thank you..

**Pull request merged**
