### PR TITLE
Added details for box-shadow

### PR DESCRIPTION
**Pull request by HebleV**
Added details for box-shadow

### CODE REVIEW

**Comment by texas2010** [comment]
sorry someone did write article

**Comment by HebleV** [comment]
Sorry but this was written as a stub then. Can you elaborate a bit more?

**Comment by texas2010** [comment]
@HebleV I close this because someone did write this article but someone got this first. that is why this file has a conflict. sorry.

**Comment by HebleV** [comment]
Oh no problem. I just saw it was stub so wrote it. Thank you

**Pull request closed without merging**
