### PR TITLE
Added More Information section with Video Link

### PR DESCRIPTION
**Pull request by DaricusDuncan**
**Included** the more information section back into the file.
**Added** a video link to Youtube.com where HackerRank explains Linked Lists.
**Video Link:** https://www.youtube.com/watch?v=njTh_OwMljA

### CODE REVIEW

**Comment by Hijerboa** [comment]
Hey @DaricusDuncan 

So I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

---

> If you're not familiar with the merge conflict process, feel free to look over GitHub's guide on ["Resolving a merge conflict"](https://help.github.com/articles/resolving-a-merge-conflict-on-github/). 🔍️
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝

**Comment by DaricusDuncan** [comment]
@Hijerboa Thank you so much for reaching out. I am looking into this issue and will be resolving it soon.

**Comment by DaricusDuncan** [comment]
@Hijerboa  Did my changes fix the issue?

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit e68052a3bfce305534659435502568bdc034cb0a

https://deploy-preview-2867--guide.netlify.com

**Comment by DaricusDuncan** [comment]
@BerkeleyTrue I see it now. It does not look the best. There are some format issues that need to be adjusted. When I implemented this change, I did not see the part explaining the linked list. 

How can I roll back this merge and readjust the presentation of the text?

**Comment by Hijerboa** [comment]
@DaricusDuncan sorry it took me so long to reply--
I don't see any issues with the formatting at the moment. Perhaps I'm missing it? 
If there are no issues with the formatting, I can merge this whenever you like! :)

**Pull request closed without merging**
