### PR TITLE
Fix More Info section in Common Ruby Arrays Methods article

### PR DESCRIPTION
**Pull request by thomaskuntzz**

### CODE REVIEW

**Comment by nsuchy** [comment]
Hey @ thomaskuntzz

So I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

---

> If you're not familiar with the merge conflict process, feel free to look over GitHub's guide on ["Resolving a merge conflict"](https://help.github.com/articles/resolving-a-merge-conflict-on-github/). 🔍️
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝

**Comment by nsuchy** [comment]
Hey @thomaskuntzz

So I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

---

> If you're not familiar with the merge conflict process, feel free to look over GitHub's guide on ["Resolving a merge conflict"](https://help.github.com/articles/resolving-a-merge-conflict-on-github/). 🔍️
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝

**Comment by nsuchy** [comment]
Opps I didn't intend to send that comment twice.

**Comment by nsuchy** [comment]
@thomaskuntzz I went ahead and resolved your merge conflicts - I'll merge once the checks pass 👍

**Comment by thomaskuntzz** [comment]
Thanks!

**Pull request merged**
