### PR TITLE
Renamed more certificate to match challenge names. Moved Algorithm Pe…

### PR DESCRIPTION
**Pull request by iabrenne**
Renamed more articles in the certificates section to match the name of the corresponding challenge. Also moved Algorithm Performance articles from certificates to the algorithms section.
This would be a partial contribution for [16388](https://github.com/freeCodeCamp/freeCodeCamp/issues/16388).

---

## ✅️ By submitting this PR, I have verified the following

- [] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by iabrenne** [comment]
Hi @nsuchy. Sorry I am still pretty new at this and never dealt w/ a merge conflict before. Not quite following, though, why there would be a conflict with these two files, P

**Comment by iabrenne** [comment]
@nsuchy - I am using text editor and git on the command line. I'd be happy to fix it if you guide me through what I need to do. Thank you!

**Comment by nsuchy** [comment]
@iabrenne Awesome, so if you aren't using something like Atom or VS Code that does this for you you'll have to go by command line which can get tricky but once you get the hang of it it's a valueable still to have. I'm assuming you've never resolved a merge conflict before.

To simplify what happened you've requested to change a line of code, afterwards someone else changed that same line of code, you'll have to review both lines and select which version of the line you'd like to keep. You should be able to run `git mergetool` once you are on this PR's branch and it will walk you through the conflict in vimdiff, or a gui tool if you have one installed. Text editors like Atom and VS Code have easy interfaces to resolve merge conflicts quickly.

I know was a lot to read, look it over and let me know if you're still confused and I'll try to help :)

I recommend reviewing the following resources for a further understanding:
* [YouTube - freeCodeCamp - Git & GitHub: Merge Conflicts](https://www.youtube.com/watch?v=sfT0WrChMrM)
* [Stackoverflow - How to resolve merge conflicts in Git?](https://stackoverflow.com/questions/161813/how-to-resolve-merge-conflicts-in-git#163659)

**Comment by QuincyLarson** [comment]
@iabrenne Thanks for opening this PR. I'll take care of these conflicts and get this merged so we can keep moving. :)

**Pull request merged**
