### PR TITLE
Add a code of conduct

### PR DESCRIPTION
**Pull request by systimotic**
The exact same as [the code of conduct from the main repo](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CODE_OF_CONDUCT.md).

A code of conduct doesn't hurt anyone and can help everyone. By adding a code of conduct, I hope that we're setting in stone the things we already try to do, and make them visible to others.

### CODE REVIEW

**Comment by systimotic** [comment]
@dhcodes Awesome, thanks for the review! ❤️  I didn't request your review because I wasn't sure if you were around, and I didn't want to bother you if you weren't. I still appreciate your review!

**Comment by Bouncey** [comment]
## LGTM

:sparkles: :sparkles: :sparkles: :sparkles:

**Comment by HKuz** [comment]
Hi folks - sorry I wasn't around much yesterday! I'm taking my nephew up to New Hampshire this weekend and had to get a bunch of things ready, including installing a simple car seat in my car for him. Let's just say that was a humbling experience... Anyway, I agree with others, having the Code of Conduct in place is a great idea, thanks for including this @systimotic ! 🎉

**Comment by dhcodes** [comment]
@systimotic I wasn't meaning to put off a self-pity vibe :) Communicating via text is hard. Good work all around!

**Comment by systimotic** [comment]
@HKuz No worries! I hope you had fun with your nephew 😃
@dhcodes Don't worry, I didn't get that vibe, I just still felt the need to explain why I didn't request your review 😅

**Pull request merged**
