### PR TITLE
Add minor correction

### PR DESCRIPTION
**Pull request by DamianRivas**
Replace this sentence with a brief description of the awesome changes your PR has. 😊

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/.github/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by DamianRivas** [comment]
@johnkennedy9147 Can you elaborate? I know I didn't add content, but I figured the improvement, although small, was appropriate for my first ever contribution to an open-source project.

**Comment by Hijerboa** [comment]
@DamianRivas the reason it was closed is due to the fact that you did not follow the FCC contribution guidelines.  You'll notice that when you submit a PR, you need to add a description of your changes, and if you do not add one, it appears like it does here-- as a generic message. Please change that you and you should be able to reopen the PR and have it accepted.

**Comment by DamianRivas** [comment]
@Hijerboa Got it. I figured the change was self-explanatory to anyone reviewing the files changed tab, but rules are rules. I'll give it another shot, thanks!

**Comment by jamesjpk123** [comment]
It looks like this PR can be reopened @DamianRivas now that you have added the description, but I cannot do this. Only someone with write permission can. May @johnkennedy9147 help out with this? Or do you have any other recommendations @johnkennedy9147?

**Comment by johnkennedy9147** [comment]
replaced by PR #7853

**Pull request closed without merging**
