### PR TITLE
Javascript: create javascript/css dropdown tutorial

### PR DESCRIPTION
**Pull request by GCrispino**
Tutorial created to replace [this](https://guide.freecodecamp.org/javascript/tutorials/how-to-create-a-dropdown-menu-with-css-and-javascript) stub.

Just now, after finishing this tutorial I've realized that there's another pull request(#7809) for this same tutorial(that honestly looks better than mine), but since I've already finished it I figured there's no harm in opening this PR. If this is wrong a maintainer can close this. Thanks 😄 

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by GCrispino** [comment]
@nsuchy Awesome, thanks! But why was the other PR invalid?

**Comment by nsuchy** [comment]
@GCrispino It just deleted content and left the stub blank rather than adding it. It also deletes the header of the stub causing a build failure at runtime so I couldn't merge even if I wanted to allow it because it'd break the entire site. That said your changes are merged 👍

**Comment by GCrispino** [comment]
Hmmm, that's true, but weird. There's this [this](https://github.com/freeCodeCamp/guides/pull/7809/commits/1ad277196855029ca3b83a5811178568d1ea50dc) change in this commit that basically adds the whole tutorial, but I don't know why [this](https://github.com/freeCodeCamp/guides/pull/7809/files) page does not show this stuff 🤔

**Comment by GCrispino** [comment]
Oh, I see!

**Pull request merged**
