### PR TITLE
Fix title of folder.

### PR DESCRIPTION
**Pull request by jamesjpk123**
Fixing title of the folder called "why-does-free-code-camp-uses-javascript-instead-of-ruby-or-python" to "why-does-free-code-camp-use-javascript-instead-of-ruby-or-python" to fix grammar, and be consistent with the title inside of index.md.

### CODE REVIEW

**Comment by texas2010** [comment]
change a what? please put it in description. not PR title.

**Comment by jamesjpk123** [comment]
Yeah sorry, here changing the title now.

**Comment by texas2010** [comment]
it seems it is the same thing to me. can you tell me? I cant see what difference is.

**Comment by jamesjpk123** [comment]
Changes the word "uses" to "use" to fix a grammar error. It was supposed to be fixed in #419, but @davidluhr forgot to change the folder name.

**Comment by texas2010** [comment]
@jamesjpk123 thanks for explaining!

**Pull request merged**
