### PR TITLE
fix C++ syntax highlighting

### LINKED ISSUE #233: Snippet and Image links Broken ?
So, I have written the intro guide under C++ in guides.
The code snippet does not show the last 2 lines 
```C++
<endl;
return 0;
}
```
and the image link doesn't show the image but shows the title I have given it.
All other image links are not working 😭 
Can anyone help me out to solve this issue?
The Main website : 
image

The GitHub output for the article I've written :
image
 The code for the same : 
image

Help needed ASAP so that all other articles written by me do not have this issue .
Thanks.
Hitarth.

### PR DESCRIPTION
**Pull request by sappharx**
Closes #233 `# Bouncey`

This fixes the C++ syntax highlighting that was breaking the entire C++ page (well, everything after the first code block).

The reason denoting a C++ code block with ` ```C++ ` in markdown is a problem:

When the markdown parser encounters this code block it creates a `code` node with `node.language = 'C++'`. When Gatsby gets around to executing the `gatsby-remark-prismjs` plugin it looks for `Prism.languages['c++']`, which it won't find because the C++ language is defined as `cpp` in PrismJS), so it bails and just returns the plaintext of the code block without highlighting it (PrismJS would work its magic and escape characters appropriately).

Similar issues might exist for other language types, see #362

Further reading:
https://github.com/wooorm/remark/tree/master/packages/remark-parse
https://github.com/syntax-tree/mdast#code
https://github.com/PrismJS/prism/blob/gh-pages/components/prism-cpp.js
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/index.js
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/highlight-code.js
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/load-prism-language.js

output html for 1st C++ code block before:
```html
<div class="gatsby-highlight">
      <pre class="language-c++"><code>#include <iostream>
using namespace std ;
int main()
{
    cout&lt;&lt;"Hello World"&lt;<endl; return="" 0;="" }<="" code=""></endl;></iostream></code></pre><code>
      </code></div>
```

resulting broken page:
screenshot 2017-09-30 21 05 41

output html for 1st C++ code block after:
```html
<div class="gatsby-highlight">
      <pre class="language-cpp"><code><span class="token macro property">#<span class="token directive keyword">include</span> <span class="token string">&lt;iostream&gt;</span></span>
<span class="token keyword">using</span> <span class="token keyword">namespace</span> std <span class="token punctuation">;</span>
<span class="token keyword">int</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    cout<span class="token operator">&lt;&lt;</span><span class="token string">"Hello World"</span><span class="token operator">&lt;&lt;</span>endl<span class="token punctuation">;</span>
    <span class="token keyword">return</span> <span class="token number">0</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre>
      </div>
```

resulting fixed page:
screenshot 2017-09-30 21 07 09

### CODE REVIEW

**Comment by sappharx** [comment]
There seems to be an error in the Travis build pipeline

[The command "sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"" failed and exited with 1 during .](https://travis-ci.org/freeCodeCamp/guides/jobs/281815599#L430)

**Comment by Bouncey** [comment]
Build restarted

**Comment by Bouncey** [comment]
Great find on the c++ vs cpp

Thanks @sappharx 👍 

:sparkles: :sparkles:

**Comment by sappharx** [comment]
Oh man, I didn't even realize that #233 existed and so much effort had been put into this already.

**Comment by Bouncey** [comment]
Thanks for taking it on! I didn't even get as far as checking what `prismjs` was looking for

**Pull request merged**
