### PR TITLE
Go: wording of introduction.

### PR DESCRIPTION
**Pull request by weakish**
Remove redundant word ("feature" appeared twice).

### CODE REVIEW

**Comment by Asjas** [comment]
Hey @weakish 

I'd love to be able to merge your changes but it looks like there is an error with the Travis CI build. ⚠️

Once you resolve these issues, I will be able to review your PR and merge it. 😊

---

> Feel free to reference the [Article Style Guide](https://github.com/freeCodeCamp/guides#article-title) for this repo on formatting an article correctly so your Travis CI build passes. ✅
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝
Unfortunately your PR is failing the Travis Build. Please refer to our [Style Guide](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md#article-style-guide) on how a article should look.

**Comment by weakish** [comment]
@Asjas I only edited one markdown file, nothing else. I did not know why Travis CI refuses to build this. And I have no idea how to resolve it.

**Comment by Asjas** [comment]
@weakish The build error is `Error: ENOTDIR: not a directory, open 'src/pages/java/data-abstraction/index.md'`.

I noticed your repo does not have this file but the main FCC Guide repo does have it. I would suggest you follow the [Contributing Guide](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md#cloning-locally) on how to update your fork of the Guide and then update your PR.

**Comment by weakish** [comment]
The build error is because the base of this PR is slightly outdated.
I rebased the commit and sent a new PR #8005

**Pull request closed without merging**
