### PR TITLE
Added a hash table document description 

### PR DESCRIPTION
**Pull request by mtpjr88**

### CODE REVIEW

**Comment by Asjas** [comment]
Hey @mtpjr88 

I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

Once you resolve these conflicts, I will be able to review your PR and merge it. 😊

**Comment by mtpjr88** [comment]
OK great! I will fix them.

**Comment by mtpjr88** [comment]
can i still get them merged if it has been closed?

**Comment by Asjas** [comment]
Hi @mtpjr88. Yes all you need to do is fix the merge conflicts and push the updated code. I will then review and merge it.

**Pull request closed without merging**
