### PR TITLE
Initial article for JavaScript typeof

### PR DESCRIPTION
**Pull request by ksjazzguitar**
This is my first try at this, please let me know if I'm not doing this correctly

### CODE REVIEW

**Comment by IsaacAbrahamson** [comment]
I have a couple comments. Some of the code you have is not directly related to typeof, and could possibly add some confusion. For example, you define a somewhat complex function:
```javascript
function pickHobby(hobbyIndex) {
  if (hobbyIndex<0 || hobbyIndex>hobbies.length)
    return "I don't recognize that hobby.";
  else
    return "Let's do " + hobbies[x] + "!";
}
```
this has absolutely no bearing on typeof, as you just do this below:
```javascript
console.log("typeof pickhobby: " + typeof pickHobby);
// typeof pickhobby: function
```
What you have in the function doesn't change typeof, it could only possibly add confusion. Maybe just a basic function would be simpler?
```javascript
function pickHobby() {
    return hobbies[0];
}
```
My opinion for the console.logs. I think it might be good to add a space to reduce ambiguity. Just by looking at the comments, it is hard to tell right off bat whether the comment is for the log above it or below it. Maybe a line space between the logs would explicitly show which comment is for the log? Also, would it be better to simply log the typeof and not the string? I think making the guides as basic and simple as possible is a good thing. Thus
```javascript
console.log( typeof hobbies);
// object
```
would be preferable to
```javascript
console.log("typeof pickhobby: " + typeof pickHobby);
// typeof pickhobby: function
```
as it shows only typeof and nothing else to consider. What do you think?

**Comment by david-daly** [comment]
@IsaacAbrahamson @ksjazzguitar I also have a pull request for adding a typeof article that has been open for 3 days #365 

Should we try to merge both of these articles, or just merge one or the other?

**Comment by ksjazzguitar** [comment]
@david-daly I'm new to this and it sounds like you were first. Feel free to merge or not merge what you want from mine.

**Comment by HKuz** [comment]
Hi everyone! Thanks for working together on this article. As @david-daly pointed out, there was another PR opened for it that I just merged. There's been a huge response from contributors since the announcement of the Guide, and unfortunately, a few collisions to edit the same article (typically, we try to favor the older PR when that happens). 

@ksjazzguitar - I'm going to close this PR given all the conflicts, but feel free to check out the article as it stands and open a new PR if you have any suggestions/edits! Thanks, all for contributing ✨ 🎉 🎊

**Pull request closed without merging**
