### PR TITLE
Pygame

### PR DESCRIPTION
**Pull request by RolphYnis**
**Game Development with Pygame**

Pygame is an open source, cross platform python library used for game development, written by Pete Shinners.

**Overview**

The project started in the year 2000 as a result of the death of PySDL. The Pygame library version 1.0 was 
released after six months development in April of 2001.

### CODE REVIEW

**Comment by erictleung** [comment]
Please add the information into the article file itself, not just an empty file. Please and thank you!

**Comment by RolphYnis** [comment]
Thank you, I think I've got it right this time.


________________________________
Från: Eric Leung <notifications@github.com>
Skickat: den 21 oktober 2017 18:04
Till: freeCodeCamp/guides
Kopia: RolphYnis; Author
Ämne: Re: [freeCodeCamp/guides] Pygame (#2720)


Please add the information into the article file itself, not just an empty file. Please and thank you!

**Comment by erictleung** [comment]
Please add the title in the correct format https://github.com/freeCodeCamp/guides#article-title

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit a6a0703aef1a4432a67c55f47a8868649de3edb1

https://deploy-preview-2720--guide.netlify.com

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit d124f0873e3cd856220da56c7d3a6035a5163406

https://deploy-preview-2720--guide.netlify.com

**Pull request merged**
