### PR TITLE
Formatting/added to overview to Unity

### PR DESCRIPTION
**Pull request by Fullmight**
Added a history section for several points that were copied from the wikipedia article that aren't really relevant information on current version unity.

Added two paragraphs of summery about unity in terms of what it is and isn't good at. Probably could use some additional filling out as these are based on my personal experience with the engine over the last year.

### CODE REVIEW

**Comment by texas2010** [comment]
Sorry, someone did write this article.

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (121/100 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f54.google.com ([209.85.218.54]:44684)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5JiE-001bFJ-5m
	for pawan@oss-india.net; Fri, 20 Oct 2017 04:25:01 +0530
Received: by mail-oi0-f54.google.com with SMTP id v132so17474394oie.1
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 15:54:29 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:cc:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=AQZ3aOk7ISoaWebdPRDJfDW3affk4THRT9PXGyYx1O4=;
        b=tawmNBKepf29zDpQ3kRcJi5FUsaxHWQaGyqrE2LUwLLauLIYWQXQ7edNXvKBDadkud
         /myjJt42TgWbzZu8oj9mrpBIMIXFKAq+VEbHXOoggG5ddEE9jNifSyMSTx9ZmaqQX5GX
         PHvlTGGtCICTsWottqoFsVfmP8Us4ETJqydI+4qLNAx/FomIb1c8DzbQdzimN84SUf0K
         d7FnkkfixGetMoXMoX7A8PXRKKwwylpu2zZ3lO9IKPi2LDWx8wEDhta53d1t1V5enblQ
         S+PKZLoW7Bdd8YxlunnljtlXsbm2XGwGe/ikFuyxMkLrJfpLfp5cBCi/IsjizMXNuXrC
         wTlA==
X-Gm-Message-State: AMCzsaWZecY0kvD5DRbWQ/KfmjZlIU07ichFVrIzSvImDsl2o/S5rxfQ
	RuB8pBdOdzw6NOoySKMpwK1S475veMhFeWcG1QWxMIImGihP8gs=
X-Received: by 10.157.4.39 with SMTP id 36mr1863196otc.490.1508453646944;
        Thu, 19 Oct 2017 15:54:06 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4404115ofa;
        Thu, 19 Oct 2017 15:54:06 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+QKdsZAf9MYmyT2szmiM3e508nnfTSb6QuWH4TJL7Uo4tdI7RiVdhglqi8YdyDWG4a+ER4w
X-Received: by 10.28.140.13 with SMTP id o13mr15947wmd.150.1508453645970;
        Thu, 19 Oct 2017 15:54:05 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508453645; cv=none;
        d=google.com; s=arc-20160816;
        b=vJb2VxODJkbQzllnW/Fbhz/F07DzaVa/qzEnJurSDV0ahhHEaXh2zcIl5JObaOXIPq
         8qPFqdxPCRnypaNBB8uTAN/mgXa8Zy1c0NobWhRrM/Z0MaRpwXMrNfiThJVe3VM/YF/i
         HW3Wl9oX/4r5Qj+vno9enAWOqNRLnYvLVVXPlfNwRfAkgayt4KhYhu0PxgWY+YyUuwIM
         dbRS2y5D5y+kTOn0c2E651zSkBkN6BApWwOIGR9Ky3NgVn9FtAv+GhqhXfSwaFnUyKgR
         kWtXpDw6ty2fo78HNh1MUvxKxzp77sXKvm0CAqHOXaezbiMny5LKxsp8VOeSJq0cpsDc
         v72g==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:dkim-signature:date
         :arc-authentication-results;
        bh=AQZ3aOk7ISoaWebdPRDJfDW3affk4THRT9PXGyYx1O4=;
        b=yPlurlbNUfuEjWMlDMkiqUzoDGclCoJTpWI2wksUTPZkpzGYCtkCIGJUm9+HJ/Ue2p
         f/xHXkAClPBUd5N3foXROAgGfvaDOXaQ0DlqlvxHOR66B7ADSn3CZAvZVaE3yOO2+A+5
         q+RggD0vSeX7gxt4Fi1ifusi3mKNMAE3qdLXXjGJw2KyXiUPaW9swJpcBbn1eLRaqmRO
         09tSaDbA1paJeuzNpN51DWjaLV5BJx/dusI8hG0cADOov8euM/cexvY1GP5Jh/ZAF0CG
         XANgmMBB4eW4s4ucSoxrCRKRmVYJcrozuONfpvT/beNCyxj+pxiJM6b914VChN9b0l6O
         hh/Q==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=k5gOvkmQ;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2-ext3.iad.github.net. [192.30.252.194])
        by mx.google.com with ESMTPS id l3si1880105wmi.244.2017.10.19.15.54.05
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 15:54:05 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) client-ip=192.30.252.194;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=k5gOvkmQ;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Thu, 19 Oct 2017 15:54:04 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1508453644;
	bh=AQZ3aOk7ISoaWebdPRDJfDW3affk4THRT9PXGyYx1O4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=k5gOvkmQLWWvNJEs+FCAFRjn1H4AjnC8c3Ra794QELv0iQiklupDzirAhDxP94ogU
	 N+qKvburtEgBzgaE9FgSwRASxL9PRNoUpMAFi1xPnYQ3eRY8KHYTOmzpij3CKaMrxX
	 R3X08huncldCcC0KTakfD0w7/xeXUkwBbmO3owpA=

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (120/100 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f45.google.com ([209.85.218.45]:56700)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5JiE-001bFL-Dh
	for pawan@oss-india.net; Fri, 20 Oct 2017 04:24:58 +0530
Received: by mail-oi0-f45.google.com with SMTP id v9so17450728oif.13
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 15:54:29 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:cc:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=8r3ZgmXkd+WPG3w0NtJwxszhsAreswVvcY1ed2POi2U=;
        b=VH5vhaB9cEhAhY5NGWzS+D69WXQzqE4ZKKy1mY4yCQoBgOTW9eqz7n8wKCW6IWCS+W
         6aHRw7u7k/MyVrMgcckSSo2vSpB3nMkQAC5OD2Uc9um4D+KwxNVtgISIjGxm2KLaNU4j
         zXq8DBqM2cyv8vyK+YMhkQD3TxYnyCLHenKDaJd+2MgRx3t3NYWn11vCxuyg0fNotXPA
         FWPttoMnN4XQ0MrvjBeN0pGmN4zpojl4tf9+Ba3BmLpCcdCeI+4SNuZ56TmkeMlBFg2d
         iHUcJsh+ICBA0VGMUvmjHFygkxvek5x5ID4+11uY1sCf86k8+az64Ya7DLJuxtKTJC6Y
         EM6w==
X-Gm-Message-State: AMCzsaVt2SR9X8I4iNd8vHLhbg3KZ2OUXPtKEqINDpO5JKBxf8qen38T
	9cmrQ1TI5qbr1TI7DmSJOKaYFofyciwNLXt7fJD0XcCQwOkBUdw=
X-Received: by 10.157.37.27 with SMTP id k27mr1809306otb.16.1508453647447;
        Thu, 19 Oct 2017 15:54:07 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4404124ofa;
        Thu, 19 Oct 2017 15:54:06 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+QdU44JUwq99CDY9rzlUTFP2H3HUFXpuLcrDFQli8pkNvMc1sRDd1l8gsuj3eo5EzQ/+WDF
X-Received: by 10.223.170.197 with SMTP id i5mr2990212wrc.118.1508453646186;
        Thu, 19 Oct 2017 15:54:06 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508453646; cv=none;
        d=google.com; s=arc-20160816;
        b=aatVhxIt3SmH8fEQWR1Om4wXuQZe0/tuvFsNyYHgK03hKzp4DX6gwMb6wfyB4XTTki
         ++RTleLXQEOQzbjXcpjs3WyNSpLkCiJKBY8kQDDKbsOsdD6DSpr/Sp3BqnTwKxowQkHU
         PGqUTQ3CkaOBKjFSJpdGsssPbPlnAEz7oGs/uldCWOiZZ4E2SUIeLvAmjJzJ6fk82mJ2
         +7IVg3msrwWo2nArverQ5PDKTBuE8S+CU3J+pWbkax8IrleHC6lzfetxYUHxQkrJ7A5Q
         1eZnHOT4RirDRumWFPWMmWxqV4tK/JfJS9OWE/qUHu5F3JVOVRenNC/ZTbwiNZ+bI+Yt
         YMXA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:dkim-signature:date
         :arc-authentication-results;
        bh=8r3ZgmXkd+WPG3w0NtJwxszhsAreswVvcY1ed2POi2U=;
        b=HytbX2rUEBRwAbJgQJc1NBOBjDmRf0Dx4ykFCjzkTjbhCibdqbbMd6tpuwTXQp/xdh
         Fc8S8vyu7yR3bTD4txj0UommKG4uYVfCeiae4pWKyFYu1Lq+3H5ka80h1wyHhv6RcEfd
         luX7X51fD04F/5ksUWstqCwpJmeUZgz11rsB2OvUgLKhngwmkZr42lyHf5lKv/VRyp4L
         tfgN09k9/m6nW95N80Bv5VoVGpIFPR00djMPQgEIx6olkd0fquVS71SlZqrPqsPyKPGv
         LFr96LM2JFDJHzguHVe8ByntFS9RNeSz5X83LwuLJoeoPaVkrg62Q2Q+S1hLSc1WZhPM
         lDiw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=nWZTVXqA;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.193 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2-ext2.iad.github.net. [192.30.252.193])
        by mx.google.com with ESMTPS id s186si1821066wmb.158.2017.10.19.15.54.05
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 15:54:06 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.193 as permitted sender) client-ip=192.30.252.193;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=nWZTVXqA;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.193 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Thu, 19 Oct 2017 15:54:05 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1508453645;
	bh=8r3ZgmXkd+WPG3w0NtJwxszhsAreswVvcY1ed2POi2U=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=nWZTVXqAm/EDDOLXfzqh7Hj3qxQEMcduHtnhRHR+8VWmmiAi8lAZ3+g9MX+7IRuYg
	 OBX5ZkT2+DMufMEUPKTfFZkowwA/70rKPNZUILCRfgLZ5AKRbHQ6aI2aS+Es8E+PSG
	 qu3YTrNT26gzNs/AKJIXndiA6wQ5XHjNVZjfQwWo=

**Comment by Fullmight** [comment]
I don't understand, what's the issue?

**Comment by texas2010** [comment]
@Fullmight, the reason is I close this because someone did write this article. plus this PR has conflict.

**Comment by Fullmight** [comment]
The current version is the version I edited, which is just a copy-paste of the wikipedia article on unity. While that does cover a lot of basic facts about the engine, it isn't very well formatted for a current-day informative article on the engine. It doesn't really do anything to explain what Unity3D is good at, primarily used for, or bad it. It also puts a bunch of historical information that just isn't useful to anyone trying to learn about Unity today right at the top of the body.

Which was why I added brief summaries of those things (except cons, and really an actual pro-con list would probably be good too), as well as moved some not particularly useful information on the history of the engine into a separate section so someone reading the article would get everything they would likely want to know out of an overview of the engine in the first two paragraphs.

**Comment by texas2010** [comment]
okay. then improve on that article. and send new PR

**Comment by Fullmight** [comment]
That's exactly what this PR was, but I'll give it another once over and resubmit.

**Pull request closed without merging**
