### PR TITLE
Updated index.md with information about mean

### PR DESCRIPTION
**Pull request by Dormanator**

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
@Bouncey please trigger a Netlify build on this :heart:

**Comment by Ethan-Arrowood** [comment]
Blocked until Netlify build preview is run and deployed.

**Comment by Bouncey** [comment]
This is an interesting one, I can't trigger a build because Netlify doesn't know about it.

I'll see what I can do

**Comment by 1andee** [comment]
That should do it 🙌

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit 96eaa6afafc878a164484751f10169a87cf68733

https://deploy-preview-2731--guide.netlify.com

**Comment by Bouncey** [comment]
Thanks @Dormanator :+1:

**Pull request merged**
