### PR TITLE
Added Supervised Learning

### PR DESCRIPTION
**Pull request by plasmatiger**
Gave a brief description about flavor of supervised learning

### CODE REVIEW

**Comment by Hijerboa** [comment]
Resolved merge conflicts

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit ca1318e7eaf5f4129998c5234159b4a135e8c628

https://deploy-preview-2910--guide.netlify.com

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit c2916ab5e77f3aaba6e58a5d441df0fc8c842c8b

https://deploy-preview-2910--guide.netlify.com

**Comment by Hijerboa** [comment]
LGTM! Thank you for contributing!

**Pull request merged**
