### PR TITLE
Improve Navigation Styling

### LINKED ISSUE #328: Improve navigation
If the navmenu isn't going to be fixed to the side, we should include a 'return to top' button/icon. Or we should make the navmenu fixed to the side of the screen so even when we scroll down on a long documentation page we can navigate to the next page easier.

This issue is open for feedback, I'm also happy to work on the CSS/JS required to make it happen.

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Ref #328 Fixed sidenav as well as search bar. Made them static so that user can read the articles then quickly navigate to the next subject. Closes #328

### CODE REVIEW

**Comment by Bouncey** [comment]
@Ethan-Arrowood Can you rebase this, `main.css` in now `main.scss`

**Comment by Ethan-Arrowood** [comment]
@Bouncey for sure. I'm having some issues with Yarn at the moment so once I remedy that I'll be pushing these changes.

**Comment by Ethan-Arrowood** [comment]
@Bouncey I'm having a stupid Git issue. I ran `git rebase upstream/master` on this branch of my local repo and it just copied my code to the main.scss and Layout.jsx files and now won't let me commit because it says no changes were detected. Any clues?

**Comment by Bouncey** [comment]
`git push origin Fix/NavigationStyling -f`

**Comment by Bouncey** [comment]
the `-f` flag will force the push through, use it with care though

**Comment by Bouncey** [comment]
And when rebasing in future, use `git pull --rebase upstream/master` this removes your changes, pulls down the latest version of master and then applies your changes on top

**Comment by Bouncey** [comment]
I have this on Chrome 

screenshot from 2017-09-30 08-11-10

**Comment by Ethan-Arrowood** [comment]
@Bouncey I added some media queries and fixed some of the css for an improved design. Essentially instead of the whole page scrolling I let the content scroll this way we don't have to deal with `position: fixed`. Let me know how it looks on your end.

**Comment by dhcodes** [comment]
only tested on Chrome, but **LGTM**.

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit f03a3596fb5fc244608f3aa6ebe6f4b60bfa9285

https://deploy-preview-338--guide.netlify.com

**Comment by Ethan-Arrowood** [comment]
I'll add this to my queue of issues 👍

**Comment by Bouncey** [comment]
Thanks for the fast turn around, But can we have a media query to fix this please?

mind-the-gap

Many thanks :+1:

**Comment by Ethan-Arrowood** [comment]
@Bouncey just pinging you to let you know I fixed your change request. Let me know if theres anything else needing to be changed for this!

**Comment by Bouncey** [comment]
@Ethan-Arrowood Sorry for the MASSIVE delay in this. Just updating with the current `master` and then we should be good to go 👍

**Comment by Bouncey** [comment]
Woo Hoo!! 🎉

**Pull request merged**
