### PR TITLE
feature/Adding GitHooks Stub

### PR DESCRIPTION
**Pull request by mazagatshy**
Adding GitHooks Stub

### CODE REVIEW

**Comment by texas2010** [comment]
Thank you for your pull request. Please read this [style guide](https://github.com/freeCodeCamp/guides#article-style-guide). I am closing this pull request for now. Please let me know if you have any questions.

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f44.google.com ([209.85.218.44]:47951)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5E9v-001VRL-4F
	for pawan@oss-india.net; Thu, 19 Oct 2017 22:29:13 +0530
Received: by mail-oi0-f44.google.com with SMTP id h200so15968826oib.4
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 09:58:41 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=38afwdX5AHBRp3NxUp4iE4Nb10mFxn73K1muR4d9djQ=;
        b=TEhgfak3BbIcVzLCuJNtKQbmz5NkMHs/cKYo03QEOUiuriXT1QPtW6nCBv8YVKBeIf
         ZPPD0QyYgNq1GCD1CU9fkLOMYzzq7Cv5erFI6y4B3+zufRxiAsU/oNtZ78GW1v+XI5qB
         Vh66A+PCd9DHF3sg174gSCGOcFLEGeXtgFcwvcUK2zDE1npvrGly1xd0ueDLppdsrYJU
         aY6GHcPptspDeCcnH4uL/vAhRHFMoEPWRhMXwaUkTgPU3wHwuhweqtI8DE8Otyhytigd
         buVYTIiJ8Mbgk2YxLMyOD5JTCj1hE8W1IH76kSbdKfIU8oFFluMa9qKR0eMlR6ASU3o5
         42cg==
X-Gm-Message-State: AMCzsaVYMd4dQnIgFBcoGMF6R3oF+Kp2WxnlkDr969ozP5Kl0q/TLuEb
	gVuNYAWjH0dhYvyWZpBxeaQ6Gbd465Ku/gx0fBtSTc0eklQUf2k=
X-Received: by 10.157.42.49 with SMTP id t46mr1463965ota.234.1508432299421;
        Thu, 19 Oct 2017 09:58:19 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4110646ofa;
        Thu, 19 Oct 2017 09:58:18 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+TXyofXdSpN5vgbCIfXkpKqCz9eMDZ0OO3i+OryBCt7uPZsHZUdtQ/5IiRsdEEJc4+RaAr2
X-Received: by 10.36.66.18 with SMTP id i18mr3173162itb.148.1508432298705;
        Thu, 19 Oct 2017 09:58:18 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508432298; cv=none;
        d=google.com; s=arc-20160816;
        b=COI6kSbLcG+9mx2cLDFzptCDAtdkYS9EwNKEZuwsc9ilIV64X7JccfYSk5JG+7ZPjY
         02Mvt5fOZlOFaWJhbIjJ3KSGttOX6x+FTg/SCYvq3bVmOEgWQj1ygLVbOhXONwadIo+N
         JSuqHxAFZfOIhzsqXvd30z8HthgnOZg7qmPBS8I+ursfLOFvG+C7wd+f+pUcuNTM1qo+
         x5s4F4zFfxSUIBaKGU45zQS4wYvwTYrVY10jkxJIll6rsKEqHjqlTpxsnV4V6JNh0Qmw
         brGprXoXznjBA4S+EYPZmv1j9tY5Q9k6nra5q+K9u/AjXEBMzBTdKIYLisRc1JU4N+zt
         qGaA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=38afwdX5AHBRp3NxUp4iE4Nb10mFxn73K1muR4d9djQ=;
        b=mgVD/0YIBLZqBU5baB8yieFGMXv/zmw+c0GfsGZpE4n32sMeaxCLZn+07Hf9amQkj7
         FvG1S9kxSoXTAcFMjo4t506R3UuO0zbaXR/aEMP5P1PEgSRysQq6gaQ9dAYMwiNE/DLH
         F0TsYDoEBo8MFSgw/vrYArkZHC0TEYyWyb8z9nijf15EznMTFxaqM4Ee7kqxLlyhEQVN
         Fack2FmkTug1Pm9xWihyJz0GuIuU01p8zA+i/Z4ddRpN4AlSg1ZiwOc5fSJO3IqshdGS
         TfLZI8MOEzPYk9v5gEDLxrTxN3AIRfDTb5FvW0VwjjaUOPCIQiv5FZSqchNoLWr/c2vN
         rIiQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=gDm53CkI;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=RlkqMqPQ;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o4.sgmail.github.com (o4.sgmail.github.com. [192.254.112.99])
        by mx.google.com with ESMTPS id b130si1604374itb.145.2017.10.19.09.58.18
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 09:58:18 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) client-ip=192.254.112.99;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=gDm53CkI;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=RlkqMqPQ;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=MATYBuETY5brUqNPaZ8ghIGjCB8=; b=gDm53CkIuVlcwY/8
	BbJsVvI6/RdJZ0HLiZfQBoEj+zCWpUL+1XnkZokStKbVt29fLWlgKMeQJdoDG3jf
	vVDEZ28swt+FjDm5VPumxuNs1wIp2sEaql3yzBe5oeSTzQtCUc4lsQjE10EZIS8p
	FQ7EU9ERzgc5QAV7LnB4H16tWR0=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=MATYBuETY5brUqNPaZ8ghIGjCB8=; b=RlkqMqPQXNumLUAfhd
	xN3Eb1gnZOyyKN/GPD9zdXggpbJJnucKZbGbQoeaQe/Sec372HuEhYUgK/+Mj+QM
	lUasQ6kN/yTY7VwcHiWHsesutB8J+ZZhjLV/2GTybOvc4siB5AkzIeM9wVM/ZAaW
	ziQ8ipZaebU/H6jxqZw8GFeH4=
Received: by filter0668p1mdw1.sendgrid.net with SMTP id filter0668p1mdw1-16740-59E8D9AA-1E
        2017-10-19 16:58:18.505506615 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id 2g541CYWRIegkvscAjNKrQ
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 16:58:18.118 +0000 (UTC)
Date: Thu, 19 Oct 2017 16:58:18 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f51.google.com ([209.85.218.51]:49070)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5E9u-001VRD-Fn
	for pawan@oss-india.net; Thu, 19 Oct 2017 22:29:15 +0530
Received: by mail-oi0-f51.google.com with SMTP id m198so15952609oig.5
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 09:58:40 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=kVQE859i60N9jHy8lqKDj2NNf7p6TAxGqG6vaqhKAIA=;
        b=L0RMX9uRT0tDRTfnVmzN+0qgpML+8n9VEGzclCv8LarzVljslRn83sQSSOKc7w8drh
         yFfRPrNrbbgALMdEJIqPo5Faq+IHsk16OHlF+jMbybUcRwWClryA9VvgkT65+/xnSn1G
         TCERIzRqyAGkLlfF+xg20+sgMOD2BT4wJnFQjgoeYLWvv4psULXoD3bEA8Zoy19Xf/Te
         58mVflhSxAW6iIHUwTF/wSKZ9jEa6VHWmATUJly+YViY7OAAGLdHaBca0pLHIUt9b/bV
         WbJbkIlCzezZKpx4Aam8+P6yA3aAW/f9yR3QmcDFNWc+tzruAoqhhrm7xhAMrP2wOP4E
         llYQ==
X-Gm-Message-State: AMCzsaXriNc4vrJN9rJTUDIiONUQb0yDTnhCCN+NmJO2oMX7kNYEY0mV
	EES+XFR5GuW+t+H953hgydfw+7/hDsVdvuHb3pDe4CQxo6inePU=
X-Received: by 10.157.33.59 with SMTP id i56mr1469383otb.248.1508432298835;
        Thu, 19 Oct 2017 09:58:18 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4110637ofa;
        Thu, 19 Oct 2017 09:58:18 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+QQIUEYMbT/p7Hg7uTAKskRq7GABC3gbVvccKMs+15iHIHOjvFleJf96LlwlUWBBp9V9BDI
X-Received: by 10.36.65.200 with SMTP id b69mr3432793itd.116.1508432298184;
        Thu, 19 Oct 2017 09:58:18 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508432298; cv=none;
        d=google.com; s=arc-20160816;
        b=DA/pG3d6nArq+XHaVO2JI5jF501Y7k39mTHeGoCENXDL6WZ45qGAyt3svCJNHFGOfo
         H0AB5qGaRZ9Z2kkUUG4T80dHMAbLJ7FMluLmYfnpivMzr4LUOBTzU235PTVrAjf+Cohn
         EO6FR/suqgAp8q5GmFxi/fl3GsAkzTqgjUxjPdy2QDfL9BAwli7nM3uIYwTUtmODDPX8
         UyVuquDDallcTnZFaJvi/LVZYW7jItGTPrnsfNQ/d++iqK/CiwYgXVPJ8oe+Wt+NVL8J
         2QdjB+NqPEOB5vCuQCQOLRmIt+xzBCro6Q4mN7cCT74ud8Cgua+tR6aeksTek5GmA/ks
         kyUw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=kVQE859i60N9jHy8lqKDj2NNf7p6TAxGqG6vaqhKAIA=;
        b=R8HUW0G+R1LjDvvFLoGFAU6/HDymipTxOvCMErB4Bhu1YYvqa5/Le571ddh8eYMR2E
         Lyl/S2IeUGgv4/15azEYz1GBiBDYzfoVMM2kEmiPMGiCXvsYYTZ/jAmO4gI82oV1KcMx
         Vnp/32Nvrxo73qyg0O0WGIRzXOQxeOCXHqRTjzf1XXgEDJTnOmX985WNVTILypCvZjQV
         aIEvLjvllaM/oZpREBSyB7iTM86X1pVy3bNZm0ojfAyN94ORXMxqN4mppA5jgbou96Ee
         WiWuGKDUyVnfnosaRwjzKMWdB4TTjBLWI0bDEbHGwjrGJ87vWChwCuOntUfbBm//RV0A
         i2aA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=YB0AkyNx;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=NzdAoqgv;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o1.sgmail.github.com (o1.sgmail.github.com. [192.254.114.176])
        by mx.google.com with ESMTPS id m34si11255120ioi.291.2017.10.19.09.58.18
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 09:58:18 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) client-ip=192.254.114.176;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=YB0AkyNx;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=NzdAoqgv;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=KU0Oc30C8T2H1pXARWgYXX2pqsw=; b=YB0AkyNxapSXJs5q
	DWL1vbHImpU9JA7iVZBC1bXyCzqQIqUOUsSOolj0/OTAKUhFPnfmYtusfVw3hGEs
	Xht+wFncSX3tePVF3U5DPm5IYwGfsEQ73D+uzMrmI2dqKOcK6+EqxJ/uTy4FNd+7
	XIlVQJZKdWWvMJ96PDxtGgEn7mc=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=KU0Oc30C8T2H1pXARWgYXX2pqsw=; b=NzdAoqgvBYqrOl9AoR
	iNYNvUBQi10z6STEXU3Gtx+Yc8LC0tNwh3fvu8AEIjhGp2SwvPagYN0l5mRUhJjg
	tNO54qTeQZxzczTxn1mP21Ylt6mdfYql7dNxCo1X8hM+dozX2U17tSiLz1cm9LY+
	VSYIgzHwRRl5B1Zo0NxNOC02E=
Received: by filter0551p1mdw1.sendgrid.net with SMTP id filter0551p1mdw1-24399-59E8D9A9-3F
        2017-10-19 16:58:17.69629917 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id RwnobsFrRwGjFTzt5OhAoQ
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 16:58:17.481 +0000 (UTC)
Date: Thu, 19 Oct 2017 16:58:17 +0000 (UTC)

**Comment by texas2010** [comment]
@QuincyLarson please block pawan-mehta. it spam comment...

**Comment by mazagatshy** [comment]
@texas2010 thanks for your response, But I did't understand, is there a problem with the styling that I couldn't recognize?

**Pull request closed without merging**
