### PR TITLE
updated font weight and style

### PR DESCRIPTION
**Pull request by syedsadiqali**
suggestions are welcome.

### CODE REVIEW

**Comment by syedsadiqali** [comment]
@zk433 what does it mean? 
Please update your contribution to use your own words.
???? I don't understand

**Comment by zk433** [comment]
@syedsadiqali Sorry for not being clear. I would suggest using your own words to describe what font weight and font stying means, instead of using a definition taken from MDN. MDN language can sometimes be too technical and the aim of guides is to be beginner friendly. 
Maybe use some examples as well? 
For more info, please refer to the [article style guide](https://github.com/freeCodeCamp/guides#article-style-guide).

**Comment by syedsadiqali** [comment]
@zk433 thanks for the elaboration. I'll certainly do it within 24 hours.

**Comment by johnkennedy9147** [comment]
@syedsadiqali closing as stale PR. You can reopen if you make the requested changes. thanks

**Pull request closed without merging**
