### PR TITLE
JavaScript: fleshing out Random Method article

### PR DESCRIPTION
**Pull request by ksjazzguitar**
I wrote a an article on this before finding out someone already had. (I'm still figuring how this process works.) I have more extensive examples of useful and common applications of the function.

I suggest adding to the existing article thusly.

### CODE REVIEW

**Comment by ksjazzguitar** [comment]
Is there something I should do with this that I haven't done? I don't completely understand this process.

**Comment by HKuz** [comment]
Hi @ksjazzguitar - there was a conflict with your PR and the existing file, which has to be resolved before we can merge your changes in. It was pretty minor (just different formatting around the link in More Information), so I resolved it on my end. This looks good and thanks for contributing! 🥇 🏆 🏅

**Comment by ksjazzguitar** [comment]
OK, thanks, I didn't realize I had to do that too. I'm still learning. Thanks.

**Comment by HKuz** [comment]
@ksjazzguitar no worries at all 😄 - in general, we'll try to give guidance if/when we need you to do anything to get your PR merged, and if you're ever unclear, feel free to ask us questions here or in the Contributors chat room 👍

**Pull request merged**
