### PR TITLE
Reformat Markdown for REST API document

### PR DESCRIPTION
**Pull request by jjpatel361**
Should fix issues mentioned below

- Markdown Reformat 
c1

- Removing Github flavored comments 
c2

### CODE REVIEW

**Comment by Asjas** [comment]
Hey @jjpatel361 

I'd love to be able to merge your changes but it looks like you have some merge conflicts. ⚠️

There was a previous PR that made changes to the same document by removing the profanity and fixing the table. You can see how the document now looks [here](https://github.com/freeCodeCamp/guides/blob/master/src/pages/rest-api/index.md).

I'm not sure if the changes you are proposing in the PR is still needed.

---

> If you're not familiar with the merge conflict process, feel free to look over GitHub's guide on ["Resolving a merge conflict"](https://help.github.com/articles/resolving-a-merge-conflict-on-github/). 🔍️
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝

**Comment by nsuchy** [comment]
@amandeepmittal Are any further changes needed before I merge this?

**Comment by amandeepmittal** [comment]
I think it is ready to merge.

**Comment by nsuchy** [comment]
@amandeepmittal Alright, since this is already assigned to @Asjas I'm going to wait for him to provide any final feedback or further requested changes.

**Pull request merged**
