### PR TITLE
color description.

### PR DESCRIPTION
**Pull request by lore-code**

### CODE REVIEW

**Comment by texas2010** [comment]
@lore-code Do you plan to write more about that right now?  it seems it is one line to me.

**Comment by lore-code** [comment]
Hi, I just wrote that real quickly to understand how pull request work in
github and open source projects.

**Comment by texas2010** [comment]
@lore-code, so you just use our repo for test PR?   right?

**Comment by texas2010** [comment]
Thank you for your pull request. Please read this [style guide](https://github.com/freeCodeCamp/guides#article-style-guide). I am closing this pull request for now. Please let me know if you have any questions.

**Pull request closed without merging**
