### PR TITLE
Addresses Issue #4517 by Adding an Article about Terminal Commands in Mac OS

### PR DESCRIPTION
**Pull request by Bentley912**
Adds an article about Terminal COmmands in Mac OS. 😊

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Deploy preview failed.

Built with commit 828a2fec06b75e62336fcb735c3dde519a8327f7

https://app.netlify.com/sites/guide/deploys/5a25cb4bdf9953427cdf8cb1

**Comment by Bentley912** [comment]
I dont know how to fix this @BerkeleyTrue. What did I do wrong?

**Comment by Ethan-Arrowood** [comment]
Closes #4517

**Comment by QuincyLarson** [comment]
@Bentley912 Congratulations on your first merged pull request to this repo! Thank you for helping expand this article! Your explanation of the command line is great!

**Pull request merged**
