### PR TITLE
Fix frontmatter for React article

### PR DESCRIPTION
**Pull request by Bouncey**
**Description**
Fix frontmatter

@systimotic 
@dhcodes 
@HKuz 
@texas2010 
@erictleung 

Can one of you please merge asap, the build is broken

### CODE REVIEW

**Comment by Bouncey** [comment]
@davcri 
@m-henderson 
@QuincyLarson 

:point_up:

**Comment by HKuz** [comment]
Done, thanks @Bouncey 👍

**Comment by texas2010** [comment]
:(  who did a broken build? oh man...

**Comment by texas2010** [comment]
oh okay. i found someone did it. he push it to master branch without use PR...

https://github.com/freeCodeCamp/guides/commit/f635b2eff3ccc4fc385a4d04eeb54fb4d4a24b65

**Pull request merged**
