### PR TITLE
Added some basic information about the <img> - tag

### PR DESCRIPTION
**Pull request by kaukasus124**
Syntax, alt and size

**Description**

### CODE REVIEW

**Comment by fvcproductions** [comment]
Hey @kaukasus124 

So I'd love to be able to merge your changes but it looks like there is an error with the Travis CI build. ⚠️

```bash
Error: ENOTDIR: not a directory, open 'src/pages/java/data-abstraction/index.md'
```

This error was not actually caused by your file but was an old error caused by merging faulty code to the `master` branch. It has since been resolved.

To pass the build, you will have to sync the latest changes from the `master` branch of the `freeCodeCamp/guides` repo.

Using the command line, you can do this in three easy steps:

```bash
git remote add upstream git://github.com/freeCodeCamp/guides.git

git fetch upstream

git pull upstream master
```

If you're using a GUI, you can simply `Add a new remote...` and use the link `git://github.com/freeCodeCamp/guides.git` from above.

Once you sync your fork and pass the build, I will be able to review your PR and merge it. 😊

---

> Feel free to reference the [Syncing a Fork](https://help.github.com/articles/syncing-a-fork/) article on GitHub for more insight on how to keep your fork up-to-date with the upstream repository. 🔄
> 
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝

**Comment by fvcproductions** [comment]
Closing for now because the PR is stale but feel free to create a new one. 👍

**Comment by kaukasus124** [comment]
nooo :c Ok i will create a new one, sorry for not answering earlier

2017-11-08 0:17 GMT+01:00 Frances Coronel <notifications@github.com>:

**Comment by fvcproductions** [comment]
@kaukasus124 No worries - let me know here what your new PR is and I will definitely review it ASAP to get it merged. 😄

**Pull request closed without merging**
