### PR TITLE
Fixed Image and Link problem

### PR DESCRIPTION
**Pull request by sanatankc**
Before Changes: 

guide freecodecamp org-css-overflow-

After Changes:
localhost-8000-

Just fixed some markdown issues.

### CODE REVIEW

**Comment by texas2010** [comment]
I don't think so. because markdown link will be converted to HTML ink in the auto script. sorry.  that is why it will be broken again.  

if you wanna to fix it. please use markdown image. try that!  thanks!

**Comment by texas2010** [comment]
i dont meant to close it. sorry.

**Comment by sanatankc** [comment]
You mean image without anchor links

**Comment by texas2010** [comment]
@sanatankc yes.

```md
![alt](image)
```

**Comment by texas2010** [comment]
@sanatankc thanks. I will test it on my computer later. and run a guide site on my computer.   I want to make sure it is ok and correct. I hope it is work. ha

**Pull request merged**
