### PR TITLE
Added Vim Section + Index.md

### PR DESCRIPTION
**Pull request by beigebrucewayne**
Created Vim section with bare bones info. Will continue to add to it. Definitely need the infamous, "how to exit section."

### CODE REVIEW

**Comment by jamesjpk123** [comment]
Fixes issue #503

**Comment by jamesjpk123** [comment]
Fixes issue #520.

**Comment by beigebrucewayne** [comment]
@HKuz should be good to go now. Thanks!

**Comment by HKuz** [comment]
LGTM!! ⛸ ❄️ 🏒 Thanks for setting these sections up, @beigebrucewayne and for the issue notes @jamesjpk123 !

**Pull request merged**
