### PR TITLE
Added link for More Information Section

### PR DESCRIPTION
**Pull request by BenThom21**

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Deploy preview failed.

Built with commit 2af81ff19fe93d5299f2710580413df89db9d446

https://app.netlify.com/sites/guide/deploys/5a2890eca114777f58d1ff7b

**Comment by BerkeleyTrue** [comment]
Deploy preview failed.

Built with commit e667240c3507618ca9e1d2e1f22543b50a708540

https://app.netlify.com/sites/guide/deploys/5a28910e0b79b72dc41b5051

**Comment by johnkennedy9147** [comment]
travis build failing 

```
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/follow-redirects/-/follow-redirects-1.2.4.tgz: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/build/freeCodeCamp/guides/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "eval yarn " failed 3 times.
```

Also number of warnings earlier in build that arenot normally there afaik,final warning - `W: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by systimotic** [comment]
@johnkennedy9147 Looks like it was a temporary issue. I restarted the build and it completed fine 🎉

**Comment by johnkennedy9147** [comment]
thanks for your help @systimotic

**Pull request merged**
