### PR TITLE
add cloud-development/ pages

### PR DESCRIPTION
**Pull request by tekbasse**
add applications framework and index.md detail

### CODE REVIEW

**Comment by tekbasse** [comment]
wrong originating branch re-posting from dev branch

**Comment by tekbasse** [comment]
Revised to remove conditions that label as 'invalid'. See PR #2887 https://github.com/freeCodeCamp/guides/pull/2887

**Comment by tekbasse** [comment]
Revised to remove conditions that label as 'invalid' See PR https://github.com/freeCodeCamp/guides/pull/7892

**Comment by nsuchy** [comment]
I am closing this as a duplicate of your other pull request.

**Pull request closed without merging**
