### PR TITLE
Added PHP Article Stubs

### PR DESCRIPTION
**Pull request by nsuchy**
This pull requests adds stubs for the PHP section.

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/.github/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive content that has been directly copied from another source.

### CODE REVIEW

**Comment by fvcproductions** [comment]
> Menu Preview

**Comment by fvcproductions** [comment]
@nsuchy I think you've made a lot of positive organizational changes for PHP content but you might want to change the naming for a lot of these files to avoid redundancy. 

A lot of folks have pointed out in the issues section that we should avoid having repetitive naming so that instead of having, for example, `PHP` > `PHP Arrays`, it would just be `PHP` > `Arrays`. 

The titles would also have to change so that the build passes.

Refer to https://github.com/freeCodeCamp/guides/issues/659 and https://github.com/freeCodeCamp/guides/issues/477.

Otherwise, great work! :smile:

**Comment by nsuchy** [comment]
I actually thought about that after submitting this pull request. I'll through those files and fix the naming. I'd like to get started on writing these articles as soon as possible so expect an update to the naming shortly.

**Comment by nsuchy** [comment]
@fvcproductions Assuming my new commit (https://github.com/freeCodeCamp/guides/pull/7869/commits/f328363b3e0155b87cceb42582222a19d6447c45) didn't break anything - this should fix the issue you pointed out :)

**Comment by fvcproductions** [comment]
@nsuchy Looks great! Could you upload the screenshots again to validate not breaking anything? 😅

**Comment by nsuchy** [comment]
I’m away from keyboard at the moment. I’ll try to get them uploaded in a few hours.

**Comment by nsuchy** [comment]
screen shot 2017-11-20 at 6 49 11 pm
screen shot 2017-11-20 at 6 49 07 pm
screen shot 2017-11-20 at 6 48 58 pm
For everyone's reference ^^^

**Comment by fvcproductions** [comment]
@nsuchy Looks great - thanks for the contribution! 😊 

I noticed that the headers are automatically made lowercase which is unfortunate since it renders as `Php` instead of `PHP`. 

However, this is more of a styling issue that I will raise for the whole project.

Going to go ahead and merge!

**Comment by fvcproductions** [comment]
@nsuchy I actually noticed some titles that weren't correctly named so I made some minor renaming fixes. Will merge once build passes.

**Pull request merged**
