### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by imnotjohn**
Beefed up documentation to have a more accessible context for beginner programmers. Included sample code to illustrate the concept of lexical environments.

### CODE REVIEW

**Comment by texas2010** [comment]
can you tell me why you use python in the javascript article?   btw that article about javascript Closures.

**Comment by imnotjohn** [comment]
haha sorry, I'll update it to .js. I added the bit about the scope to help newcomers understand because I thought the explanation of only what a 'closure' is was not enough to help a new person understand 'how' closures work and 'why' they are beneficial. Do you think it is entirely unnecessary?

**Comment by texas2010** [comment]
oh ok. no problem. I am not sure about that.  don't worry, someone will review this article. thanks

**Comment by texas2010** [comment]
this file has conflict.

**Comment by Bouncey** [comment]
Conflict resolved

**Pull request merged**
