### PR TITLE
Use Travis-CI to build site on PR

### PR DESCRIPTION
**Pull request by Bouncey**

### CODE REVIEW

**Comment by Bouncey** [comment]
@BerkeleyTrue @QuincyLarson 

Travis runs out of memory when building the site also :disappointed:

**Comment by BerkeleyTrue** [comment]
💩 

What are our other options?

**Comment by Bouncey** [comment]
Heroku? AWS? 

Each build is currently taking around 10 minutes. My system has 8GB and can build it, each netlify container has 7GB, but I don't know how much of that is taken up with the docker image. 

This build process is only going to get longer and bigger.

**Comment by QuincyLarson** [comment]
@Bouncey If you're OK with us using your system to build, then yes - let's use that. Otherwise we would need to pay DO or AWS $80/mo for a dedicated build server.

**Comment by Bouncey** [comment]
I will see if I can run the build script on the same machine the search bar currently uses so it can be automated with a webhook. 

Other wise it will be a manual process on my machine at home

**Comment by Bouncey** [comment]
I will only charge $79.95/mo 😆 😆 🤣 🤣

**Comment by Bouncey** [comment]
Hmm, I must have been right on the limit yesterday when I last built the sight, with the new contributions pulled in I cannot build the sight any more. 

I don't think gatsby is right for us at the minute :disappointed:

**Comment by Bouncey** [comment]
@BerkeleyTrue @QuincyLarson I think we need a call to hash this out. I will be available in two hours

**Comment by Bouncey** [comment]
gatsbyjs/gatsby#1651

resolves this for now

**Pull request closed without merging**
