### PR TITLE
Fill out stub with overview of moscow method

### PR DESCRIPTION
**Pull request by spitchell**

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Deploy preview failed.

Built with commit e485c696b962c7bd5da0d4a11244d7baf57a5218

https://app.netlify.com/sites/guide/deploys/5a257b0e4c4b936f63c9509a

**Comment by Hijerboa** [comment]
Hey @adiparab14 and @spitchell 

So I'd love to be able to merge your changes but it looks like there is an error with the Netlify build. ⚠️

Once you resolve these issues, I will be able to review your PR and merge it. 😊

---

> Feel free to reference the [Article Style Guide](https://github.com/freeCodeCamp/guides#article-title) for this repo on formatting an article correctly so your Travis CI build passes. ✅
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝

**Comment by spitchell** [comment]
Hi @Hijerboa. I've poked around at this and cannot tell what the issue is.

The netlify deploy log gives me no clues and having looked at the markdown I can't see what could be problematic.

**Comment by adiparab14** [comment]
Thanks for your contribution @spitchell :+1:

**Pull request merged**
