### PR TITLE
Fix/restructure directories and add intro articles

### PR DESCRIPTION
**Pull request by QuincyLarson**
I've gone through and restructured many of the subdirectories. 

I've also made sure that all of the top-level directory's index.md files are not stubs, but proper explanations - even if they're a bit skeletal. I also removed a few top-level folders where there weren't any subfolders.

Closes https://github.com/freeCodeCamp/guides/issues/145

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@Bouncey You will need to re-run the script that updates the titles and "edit this article" paths.

**Comment by Bouncey** [comment]
I can't even begin to review this on my work laptop, it grinds to a halt about 1/4 of the way down the changes section.

It looks like you have committed the output of the normalisation script, do you still need me to run it? @systimotic could you check that out?

**Comment by QuincyLarson** [comment]
@Bouncey Wow - it ran. I didn't realize it would automatically do that. That's great! So this should be ready to merge, though I'd take a look real quick first just to make sure.

**Comment by Bouncey** [comment]
## LGTM :+1: 

:sparkles: :sparkles: :sparkles: :sparkles:

**Pull request merged**
