### PR TITLE
Added support for JS Frameworks starting with Bootstrap/jQuery.

### PR DESCRIPTION
**Pull request by nsuchy**
This pull request adds in support for Javascript Frameworks. It starts with Bootstrap and jQuery as needed for many of the Bootstrap examples, however more frameworks can be added in as needed.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@Bouncey What do you think about this? Would adding additional frameworks increase page load time significantly? Is there a way to load these only for specific articles that need them?

**Comment by Bouncey** [comment]
@nsuchy this is a duplicate of #114 which you also authored.

I think to get around loading jQuery and Bootstrap.js, we can write these articles in react using `react-bootstrap`. It would require the article to have frontmatter at the top of the file, i.e.

```js
/*
---
title: Bootstrap Modal
---
*/
import React from 'react';

function BootstrapModal() {
  return (
  // your awesome article
  );

export default BootstrapModal;
```

I would need to adjust `createNavData` to account for this.

**Comment by nsuchy** [comment]
1) Forgot about previous pull request. The application has been updated a lot since then. Feel free to close that PR.
2) This was made looking at the way the newer meta tag files had been made.
3) As for createNavData would that be for using react-bootstrap did I forgot to modify that in this PR.
4) What happens over next 5, 10 years as more JS Frameworks come out? We will need a way to show examples. Loading all of them front end could be problematic, finding a way to load them on a per-article basis is critical.
5) Does React Bootstrap allow examples using Bootstrap's JavaScript?

**Comment by Bouncey** [comment]
1. no worries
2. 
3. `createNavData` takes the title field of the frontmatter and uses it as the title for the SideNav components. We would need to make it recognise the react page and not skip over it like it would do currently
4. There is scope for this to be done already, and it would require little work. I'm just very cautious...
5. With `react-bootstrap`, you don't need to use `bootstrap.js` or `jQuery`, you can just import a Modal and it will work

**Comment by nsuchy** [comment]
@Bouncey At this point, what steps would you like taken to complete this pull request.

**Comment by Bouncey** [comment]
☝️ [comment](https://github.com/freeCodeCamp/guides/pull/274#issuecomment-330030875)

`createNavData` would need to not ignore `.jsx` files and read the frontmatter to find the title.

**Comment by nsuchy** [comment]
Would not ignoring .jsx files cause a negative performance impact?

**Comment by Bouncey** [comment]
No, the only `.jsx` file in the pages dir is `Search.jsx`,  and the `search` dir is an excluded dir with regards to `creatNavData`

**Comment by nsuchy** [comment]
@Bouncey Would you mind giving me more information on how you'd like me to adjust my code so this can get merged? I am still interested in fixing this.

**Comment by nsuchy** [comment]
Closing this as I had to delete my fork and refork due to a technical issue. I will work on this again on my new fork soon.

**Pull request closed without merging**
