### PR TITLE
Added details on how to add colors in CSS.

### PR DESCRIPTION
**Pull request by HebleV**
Added details on how to add colors in CSS.

### CODE REVIEW

**Comment by johnkennedy9147** [comment]
@HebleV Hi, sorry but someone already wrote an article for this stub. Feel free to review the article and make any additions or edits, thanks for your contribution.

**Comment by HebleV** [comment]
Can you explain it more. Because when I wrote nobody had written for this stub. And now I see this. Do I have to remove the stub part i.e. " This is a stub ......... " while committing?

**Comment by QuincyLarson** [comment]
@HebleV It looks like you may have been working on this at the same time as someone else. When I check the Guide, there's already a pretty comprehensive article on this: https://guide.freecodecamp.org/css/css3-colors

This happens from time to time. It's a coincidence. In some cases, we merge conflicting text into a single article. In other cases, it's best to open a subsequent PR trying to improve upon the existing article.

**Comment by HebleV** [comment]
Thank you @QuincyLarson for the response. Looks like this is my third co-incidence. Besides, while submitting the PR, it passed all the tests with no conflicts. So it's difficult to know really if there is already one written.

**Comment by johnkennedy9147** [comment]
@HebleV Hi, the tests that run when committing a PR only check against what is already merged, any other PRs that have been submitted but not yet merged wont be checked against.  To minimise the chances of this you can search the open PRs by article title, for example ```is:pr is:open css3-colors``` its not foolproof but it would help minimise the chances of you working on something that we are not going to be able to use. thanks again for your contributions.

**Comment by HebleV** [comment]
Thanks for the help. Now I can connect the dots.

**Pull request closed without merging**
