### PR TITLE
[WIP]DevDocs-ify SideNav

### LINKED ISSUE #39: Add rel-canonical meta tag
All "re-canonical" meta tags should point to https://www.freecodecamp.org/guide/[article-specific-path]

### LINKED ISSUE #66: Make sidebar navigation like DevDocs.io
DevDocs has exceptional side navigation accordion design, and I think we should follow their example.

Basically:
- clicking on a topic should 
  1. toggle the carrot from a chevron right symbol to a chevron down symbol 
  2. expand to show that topic's children articles 
  3. show that topic's index.md content in the article view pane
- clicking the topic a second time should collapse it
- the topics should use a finger on-hover
- the side navigation pane should scroll independently of the article
- All navigation items should be the same font size and color, and we should instead use left-indention to visually indicate that one item is a child of another
- We can optionally add a number to the right-hand side indicating the number of articles.
- If possible, we should indicate that an article is a stub in the navigation to save people disappointment of clicking on it - perhaps by lightening its text-color.
- We can consider the use Font Awesome or a similar icon library to put icons the the left of top-level topics

We can then also use this same CSS for the updated challenge map at beta.freecodecamp.com/map

CC @BerkeleyTrue

### LINKED ISSUE #92: Clicking nested panels in SideNav does not make them expand
Leave a comment

### LINKED ISSUE #140: Unable to run the repo locally.
After running `yarn install` and running `yarn run dev` I am getting this in the terminal:
Is it with me or everyone else:
```
yarn run v0.27.5
$ node seed && gatsby develop
/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:77
    throw e;
    ^

Error: Error: ENOTDIR: not a directory, scandir '/home/invinciblycool/FCC/guides/src/pages/articles/sql/sql-alter-table/'
    at AnonymousObserver.listAllDirs.toArray.subscribe.err [as _onError] (/home/invinciblycool/FCC/guides/seed/_createNavData.js:50:15)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:1836:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:1772:14)
    at AnonymousObserver.tryCatcher (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:5891:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.error (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:2501:59)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:1772:14)
    at InnerObserver.tryCatcher (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.error (/home/invinciblycool/FCC/guides/node_modules/rx/dist/rx.js:5891:52)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by Bouncey**
Closes #39 
Closes #66 
Closes #92 
Closes #140

### CODE REVIEW

**Comment by Bouncey** [comment]
anim

**Comment by QuincyLarson** [comment]
@Bouncey This looks great. My feedback: 

- the sidenav could be a bit wider to reduce the likelihood of wrapping. We have plenty of horizontal real estate, at least on desktop.
- all entries should be the same font size (it looks like sub-categories use a smaller font currently)
- I noticed the top-level cateogories use a text selection cursor instead of a finger pointer cursor.
- Clicking on a sidenav element to expand it should also show the article associated with it (for example, clicking on the HTML category should show the contents of the index.md from the root HTML folder
- I think the articles without sub-articles don't need bullets. Instead the absence of a caret indicates that they don't contain any further articles.

**Comment by Bouncey** [comment]
anim

**Comment by QuincyLarson** [comment]
@Bouncey this looks great! This is just the functionality I envisioned. I also like how a top-level topic without any files has a call to contribute right in the navigation.

**Pull request merged**
