### PR TITLE
Add web components

### PR DESCRIPTION
**Pull request by SiriusScaper**
Add a shadow dom section to web components

### CODE REVIEW

**Comment by Samuel-Clarke123** [comment]
Thank you for your pull request, we always love to see active members of the community like you.
I am closing this pull request for now because I believe parts of it have been plagiarised. If you want this to be approved, please go and change those sections. Please let me know if you have any questions.

Plagiarised link:
https://auth0.com/blog/web-components-how-to-craft-your-own-custom-components/
>  Web components are a set of web platform APIs that allow you to create new...

**Comment by SiriusScaper** [comment]
I added the citation needed and did a new pr. I did not plagiarise as I cited the source in the sources section. I was going too fast with this one and probably should have spent more time on it.

**Comment by Samuel-Clarke123** [comment]
Alright, thanks for responding. 
However, we still require it to be clearer that you are quoting things. 
(Something along the lines of "According to so-and-so: ", or "(From so-and-so)")
I'd be willing to let this through if you change it like such. Cheers

**Comment by Samuel-Clarke123** [comment]
Alright. Approved.

**Comment by Samuel-Clarke123** [comment]
Alright. Approved.

**Pull request closed without merging**
