### PR TITLE
Add javascript frameworks and libraries section

### PR DESCRIPTION
**Pull request by johnkennedy9147**

### CODE REVIEW

**Comment by texas2010** [comment]
I think this pr is bad. because we have too many commits.

**Comment by johnkennedy9147** [comment]
@texas2010 yeah, I think this is because I accidentally rebased on my branch for this PR instead of master, then looked at this and went "WTF"

**Comment by texas2010** [comment]
oh dang!

**Comment by johnkennedy9147** [comment]
@Bouncey @texas2010 @systimotic is this fixable or should I close it and start anew?

**Comment by systimotic** [comment]
@johnkennedy9147 Fixed! Here's the equivalent of what I did:
```
# First, make sure you're on the PR branch. Then:
git pull --rebase upstream master
git add .
git rebase --continue
git push -f origin Add-javascript-frameworks-and-libraries-section
```

**Comment by texas2010** [comment]
@systimotic, is that for rebase the branch?  I better add that in my git note!

**Comment by johnkennedy9147** [comment]
@systimotic thanks, you're a ⭐️

**Comment by systimotic** [comment]
@johnkennedy9147  ❤️  I'm still looking for time to do a proper review of this PR. I'm sorry that it's taking a little bit, I have a lot of things to do right now.

@texas2010 Yes! Here is some clarification:
```
# First, make sure you're on the PR branch. Then:
git pull --rebase upstream master # This is how you rebase
git add . # There was a merge conflict. Normally, you'd have to resolve this in your editor and then run this command
git rebase --continue # This is to tell git that I've resolved the conflict
git push -f origin Add-javascript-frameworks-and-libraries-section # After rebasing, you need to use -f if you want to push again, otherwise it won't update the remote
```
Be careful with rebasing, as it can mess up the history of the branch. Unlike with most things in git, you can not reverse it if goes wrong. Only rebase and force push (`push -f`) on a branch that nobody else is working on.

**Comment by texas2010** [comment]
@systimotic thanks. I plan to review on rebase someday. I did learn but I forget how to do that. haha.

**Comment by texas2010** [comment]
I think we could fix it later.  more like this one is on hold for now.

**Comment by johnkennedy9147** [comment]
closing this PR due to high number of merge conflicts and with all the new articles in JS section I'll have to go through and redo the structure anyway.  I'll come back to this once we have cleared the backlog.

**Pull request closed without merging**
