### PR TITLE
Begin TypeScript guides

### PR DESCRIPTION
**Pull request by mtrivera**
This is the start of TypeScript guides for freeCodeCamp guides.

### CODE REVIEW

**Comment by systimotic** [comment]
Thanks for contributing! I don't have time for a full review right now, so I'll leave that up to someone else. I do want to share a concern: I'm not sure how this would work on a Windows system, as the `?` is an illegal character in the file system.

**Comment by Bouncey** [comment]
@mtrivera the articles look great, thanks for taking the time. However I second @systimotic's concern. But for a different reason. The directory structure in `src/pages/` will be the URL slug for the article it holds, which means we cannot have `?` in the folder title as that would be a URL query and could very well break things. 

You can certainly put the question mark the the `title` field though. 👍

**Comment by mtrivera** [comment]
Thanks for the feedback. None of this is mentioned in the **Article Style Guide**. Maybe it should discussed be in a separate **Directory Style Guide** or appended to the **Article Style Guide**.

**Comment by systimotic** [comment]
Good point @mtrivera! I've created an issue that addresses this: #250. Would you be interested in fixing this?

**Comment by mtrivera** [comment]
@systimotic Sure

**Comment by mtrivera** [comment]
See #254

**Pull request closed without merging**
