### PR TITLE
Line break added

### PR DESCRIPTION
**Pull request by BitYog**

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@BitYog Thanks for spotting this issue. We probably don't want to code HTML breaks into markdown. If you do a clean carriage return in between each link, they should all appear on their own line. Can you try this, confirm it works, and update the pull request?

**Comment by BitYog** [comment]
@QuincyLarson Done with the changes.

**Comment by texas2010** [comment]
someone did fix it.  so I close it. I checked it on the master branch.   sorry.  it makes sense GitHub tell me this file have conflict.  all good now!

**Comment by BitYog** [comment]
@texas2010 This has happened with some of my PRs. So, could you please add a CONTRIBUTING.md, with all the guidelines for PRs and issues (eg: don’t delete the fork). We could also move the writing guidelines to it. @QuincyLarson Thoughts?

**Pull request closed without merging**
