### PR TITLE
added labels to codeblocks

### LINKED ISSUE #587: HTML inside code blocks is rendered
If there is HTML (or something that resembles an HTML tag) inside of a Markdown code block, it is not escaped. It is only escaped if the language of that code block is set to HTML, or a different language that is set up to handle things that look like HTML elements.

This causes issues with HTML inside strings inside Javascript code blocks, and primarily with all of the code blocks that contain HTML but are not marked as such (there are a lot of them).

This issue is related to some problems with `gatsby-remark-prismjs`, which we use for syntax highlighting. This error doesn't happen without it.

Example (ignore all `~`, they are there to make GitHub show the things I want it to show):
```
```html
<div>
  This is not rendered as html, but as code. This is what we want.
</div>
``` ~
```

```
``` ~
<div>
  This is rendered as html, not as code. This usually messes up the page.
</div>
``` ~
```

Related: #233 #239 #246 #275 #450 #453

Still an issue with a lot of articles:
- https://guide.freecodecamp.org/certificates/create-a-bootstrap-headline
- https://guide.freecodecamp.org/certificates/create-a-bootstrap-row
- https://guide.freecodecamp.org/certificates/target-html-elements-with-selectors-using-jquery
- https://guide.freecodecamp.org/certificates/use-css-selectors-to-style-elements
- https://guide.freecodecamp.org/certificates/use-hex-code-to-color-elements-blue (:smile:)

And there are a lot more around there.

I think we should probably open an issue at Gatsby about this. I haven't been able to find anything about it over there.
/cc @Bouncey

### PR DESCRIPTION
**Pull request by smsrkr**
added syntax labels to markdown codeblocks in articles.
this should fix #587 and all similar issues. (until the underlying markdown parser bug is fixed).

targets:
- [x] label fenced codeblocks.
- [x] label indented codeblocks (after ```-fencing them).

_a lot of files got touched obviously, because there are codeblocks everywhere. touched files are stripped of unnecessary trailing spaces as well my editor (sublimetext)._

-- --
## ✅️ By submitting this PR, I have verified the following
- [x] Added descriptive name to PR
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by erictleung** [comment]
@smsrkr @nsuchy this is a massive PR and I worry this will take a lot of time to QA. Additionally, other smaller PRs that intersect with the files changed in this may introduce merge conflicts, as shown above already.

IMO, the best way to handle this may be with a lot of smaller PRs, even though it may be less efficient. It does reduce the cognitive load of QA-ing this. @smsrkr sorry, it appears you've put a lot of work into this, but just adding my two cents. Plus, breaking up this PR allows others to help contribute as well.

cc/ @freeCodeCamp/moderators Thoughts?

**Comment by nsuchy** [comment]
@erictleung Absolutely agree, merge conflicts keep occurring too. Huge PRs are difficult to review. I'm unassigning myself from this PR as a review is overwhelming to me right now.

**Comment by smsrkr** [comment]
bummer. :neutral_face:

**Comment by raisedadead** [comment]
Hi @smsrkr thanks for the incredible work that you have put in over here. We would love to have these changes.

But, the way I can see is to close this, an break it into a few files per PR, to move at a decent pace.

Thanks once again for the hard work.

**Comment by nsuchy** [comment]
Just an added note @smsrkr you could likely copy and paste your changes into the new PRs to save time.

**Comment by smsrkr** [comment]
alright. closed. thanks all for feedback. :slightly_smiling_face:

**Pull request closed without merging**
