### PR TITLE
Update index.mb to create an article

### PR DESCRIPTION
**Pull request by zkafkes**
I added information to a stub article.

### CODE REVIEW

**Comment by texas2010** [comment]
@zkafkes, do you plan to write the article about that?

**Comment by zkafkes** [comment]
I did write the article... did it not show up the right way? I haven’t used GitHub in a while and wasn’t sure if I’d done it properly.

Zoe Kafkes
zoekafkes@me.com
630-915-0053

This email has been sent from my iPhone. Please pardon any typos.

**Comment by texas2010** [comment]
@zkafkes, never mind. I see it now. I didn't notice it at first.

**Comment by MrAsrani1312** [comment]
Awesome 👍 Thank you for your contributions 😃 @zkafkes

**Pull request merged**
