### PR TITLE
Flesh out stub "Z Index"

### PR DESCRIPTION
**Pull request by IsaacAbrahamson**
Please review my guide to Z Index. Thank you!

### CODE REVIEW

**Comment by jamesjpk123** [comment]
Precedent of #429, and #481, and #519. We need to merge these commits together.

**Comment by erictleung** [comment]
@IsaacAbrahamson thanks for the PR! Sorry for the delay. From #481, it was suggested to add this line 

```
**Note**: z-index only works on positioned elements (position:absolute, position:relative, or position:fixed).
```

If you could add this somewhere within the article, that would be great!

**Comment by erictleung** [comment]
Also, maybe consider adding this link https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

**Comment by jamesjpk123** [comment]
> I definitely think the note about z index only working on positioned elements is worth bringing over 👍
was said about #481 to add over to this article.

**Comment by texas2010** [comment]
@IsaacAbrahamson, ping you.

**Comment by IsaacAbrahamson** [comment]
@erictleung, I added the changes you requested. Thanks for pinging me @texas2010. For some reason my email settings aren't working, so I wasn't notified of this thread and forgot about it until today. I was getting an email for every single thread since I am a member, so I turned my emails off for that, but now it no longer messages me at all. Any ideas?

**Comment by texas2010** [comment]
No problem. I disable Email Notifications from GitHub too. often time, I check https://github.com/notifications.

on this setting, make sure web is checked. https://github.com/settings/notifications

**Comment by IsaacAbrahamson** [comment]
@texas2010, so I take it I will only get notifications from threads I start or comment in not every thread for members?

**Comment by texas2010** [comment]
@IsaacAbrahamson no clue. you could look at this. https://help.github.com/categories/receiving-notifications-about-activity-on-github/

**Comment by erictleung** [comment]
@IsaacAbrahamson thanks for contributing! I hope you're able to fix your GitHub notifications. If you want notifications for all activity in a repository, you can always "Watch" the repository using the button in the top right. Happy coding, nonetheless!

**Pull request merged**
