### PR TITLE
React native props guide

### PR DESCRIPTION
**Pull request by gwenf**
a guide on how props work in react native.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Deploy preview failed.

Built with commit c3bf72db88993f8892f714f045ec96fb3e3d22b1

https://app.netlify.com/sites/guide/deploys/5a29bcfea6188f5732d85c43

**Comment by 1andee** [comment]
Hey @Bouncey any idea what's going on here? The error thrown in the deploy preview is unrelated to this PR: `Error: watch /opt/build/repo/src/pages/php/loops/while-loop ENOSPC`

Everything looks cleanly merged in that section of the repo -- no obvious issues present, nor is there anything of note in the commit history of that file.

**Comment by Bouncey** [comment]
Building :rocket:

**Comment by Bouncey** [comment]
Thanks @gwenf :+1:

**Pull request merged**
