### PR TITLE
Add Short-Circuit Evaluation guide in C

### PR DESCRIPTION
**Pull request by andres-uris**
Hi I create a short-circuit guide in C. Give it a look

### CODE REVIEW

**Comment by andres-uris** [comment]
Ohh the title sry.

**Comment by texas2010** [comment]
@andres-uris btw I left comment to you.

**Comment by andres-uris** [comment]
@texas2010 Yes sry I thought  that my fork was the problem. I added the title in #1798

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f53.google.com ([209.85.218.53]:47482)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5Ijv-001KvH-FE
	for pawan@oss-india.net; Fri, 20 Oct 2017 03:22:43 +0530
Received: by mail-oi0-f53.google.com with SMTP id h200so17262753oib.4
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 14:52:10 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=tON1uLncERjdD03Bha19Gvn0FXjCT3pNDcAofhqxrYU=;
        b=mq7Q6/HOu9Tlm6xCb4VYrMRCLu58S0Zuum8aPaPRW65wzGckyTp7hVOk03yk8BpJ/J
         MYM/MXRHj46MxGYZWeRF7Wg1OHR2BhijRQc9W27jtU/Wxsd3grjxv/7M0OMheHmJFDXM
         A5ll+llLhrvYVlMPuB6PDzEw4hXhe5aMyOInkhN2gi6wYzY4CzivxCQSw2FG6NtSw4V3
         hz9CrY9ZYKYum/syfTxj3e9pJ8UHhZHlhLpM80hppGEjyRNH/tQU7avt95s+REFGosMZ
         D7co2O41YpniE4CN3htkpHf36s60bKj7j0KWdM+kPj8bdoF9xSURhjFbNg1w90hXWCTm
         MHvQ==
X-Gm-Message-State: AMCzsaUnqniUHtrA2AdYNnM7Me5F7SNjcGguimD7y9QEtrLgeHVk93oO
	tY/pLwjg48RRsr0m4/PesYGDFgnGKMDOpSKtYmBPzcrZ3XJuxpo=
X-Received: by 10.202.1.81 with SMTP id 78mr1450917oib.195.1508449908698;
        Thu, 19 Oct 2017 14:51:48 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4356451ofa;
        Thu, 19 Oct 2017 14:51:48 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+TNbtbNtBF9TBHkSV43iHGo9IIqnj/PmO0si47Awb6moUy3QmC/Mp6JKXfLa4WMsq/gglpZ
X-Received: by 10.200.24.185 with SMTP id s54mr4433714qtj.328.1508449908015;
        Thu, 19 Oct 2017 14:51:48 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508449908; cv=none;
        d=google.com; s=arc-20160816;
        b=uOyI+ocXrryFJwNtFI8tapUO1V7dZrJA7krxfKjJhZpvZ5WmVICnTN2M+K8IljR6QW
         5dIt83hYY0Y6pSmcs+4ZOtGT4xwZ9MvqJakHrtobEQIFUIEGjp7zd8T3OFpY6gAwGkGh
         wleADxjV0bCKe/ZYdECEf5f5dwWdsRrYEmiYSnVcL8N7hFasD7XWHLHbnWpLG2HPwbA4
         GQUmEr687KZd3tWYlvqNYNuEMokMfHWtS/Hi+Y8+lMWg/O/hlgbB91ZmrQIdEiiU0jUc
         D5Y+kg0SRxXuREhNGvPM0lniFg5YTaj9ScRw8bDgTIP2G/Op3N3qdBUaA3Mn4DUXcQyz
         mb1w==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=tON1uLncERjdD03Bha19Gvn0FXjCT3pNDcAofhqxrYU=;
        b=jbBexT1nG82VyL0OXp9tRW7UU7dckSY+7fT+ePHNRk0pu+ymFPksF0r8MYmVPsIb4c
         Cl0DGr62WnsZ8WaSwlPhTN7iDwvPHG89GcIPE+1vxC6tEA7RpB4FKobeGD8tYFXBsFJo
         MrqCknk4BAMrx8dLg0ITk0L/wnaxTxzK3X1xNXPX1biaD4fH6pM1VztwstoNQB5l8etf
         qgiqFwj7OCFO5qtmuUwrSPKYMzZT0bEq2ZsH8TK8ETqwWEsvYnPsazQmv1RJN2fCedYg
         GJGg0cgLXmZPu5MZh/HRpUJYlbY9Lo1tzLrjqHjjjr9yMAwfILJY0lN/vO8bIWtYy68b
         dSJQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=SqA77B/z;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=V00zxZDp;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.199 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o8.sgmail.github.com (o8.sgmail.github.com. [167.89.101.199])
        by mx.google.com with ESMTPS id i46si7928820qtf.453.2017.10.19.14.51.47
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 14:51:48 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.199 as permitted sender) client-ip=167.89.101.199;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=SqA77B/z;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=V00zxZDp;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.199 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=7u4Q8J7PVpZfZrhXeueYdkUuw9k=; b=SqA77B/zOxth2eWA
	aoGLh3fn7RLjbN5mCedkMkFk7DlvLcqN4eswETlOhMF0bEhcjNe6R8GloGOvag5q
	vB4EngS5yUFIPX/Lsex42sjtqCr+1WLC4U3mw6b/CvVkLcdsdfcI0iz4y+Q5xa5i
	HVlzvcI2dBDMv9Iiwxq22SY1HDE=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=7u4Q8J7PVpZfZrhXeueYdkUuw9k=; b=V00zxZDpeeWRmbzIw6
	APnKhKwJTEA4jRsRiIxLZSIU+tv/exp/4Kh1KpA+zfCZDYF1tpx409HSqOr1ODfq
	6FfybdKgcMDJA5sf1A7Bic9B0/91sXuIu3Gv7mmePKXPjCUAoWM4XCdGjId2d1Fw
	BXeRTqIjVoS958dZllv2jEBRk=
Received: by filter0260p1iad2.sendgrid.net with SMTP id filter0260p1iad2-5543-59E91E73-16
        2017-10-19 21:51:47.646137418 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0021p1iad2.sendgrid.net (SG) with ESMTP id iDXTABeDShiTIk3r_H5HYA
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 21:51:47.762 +0000 (UTC)
Date: Thu, 19 Oct 2017 21:51:47 +0000 (UTC)

**Pull request closed without merging**
