### PR TITLE
Added - Introduction to Logical operators

### PR DESCRIPTION
**Pull request by rakhi2104**
Added related code and introduction to Logical operators in Javascript

### CODE REVIEW

**Comment by texas2010** [comment]
Sorry, someone did write this article.

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f49.google.com ([209.85.218.49]:50540)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5IiL-001KRt-IW
	for pawan@oss-india.net; Fri, 20 Oct 2017 03:21:04 +0530
Received: by mail-oi0-f49.google.com with SMTP id q4so17251121oic.7
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 14:50:32 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=Z4x6Sa5Wa1W3rpiLjgaavgksMivBnh4mWjuDtAy3jlo=;
        b=QpCV1fJq38i5KdkQsGEhnSRSFVLmaip+ukPF3S2z9itVlEnMwPeBpispOqF/vbmtz2
         grODzbMzLDl/o76jQhUFohTbp7uPptOFKeg5wU5s5WL5lS1WfH5x5JugDjZR0TQQM4ot
         oJcRpw6admyB9Tuqi4qklQriCrtuTB049KJjby/NO8sXkiVd9XqXC0C/4gyAGjeqkGCA
         h41PSjTch3EYZSYMdLsuG7/YYmbe8YJZpZDaGY9yt8WZ2s8ABU9EkTeK145eBMiLlLLz
         wlVcFWzGq/t6s2Hex7iLlkxuCPYrfbBFxOFQnUJFnpx4yreQBVGOLYif2CKV5IYxRzcI
         zwsA==
X-Gm-Message-State: AMCzsaWuxhTt9DuQac4uuPP0oZiN+IdOiEQUqKV7T0xO2xssg5lRqSoy
	F/RJ02fwNOkQ1R/r3I9OceCwgQFyzHhic2Sa6jK6+VfZgaLGSnE=
X-Received: by 10.202.207.193 with SMTP id f184mr1436982oig.65.1508449810396;
        Thu, 19 Oct 2017 14:50:10 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4355286ofa;
        Thu, 19 Oct 2017 14:50:09 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+RM0yXlaUxhPRXDLdXIg2pJg1ZJuOUf6REWC5nXny3pmxbQl2OEdy6YZ+eua2URwFvsQYkt
X-Received: by 10.36.173.72 with SMTP id a8mr3860298itj.89.1508449809728;
        Thu, 19 Oct 2017 14:50:09 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508449809; cv=none;
        d=google.com; s=arc-20160816;
        b=cPxZolv0vaCda37r/SGFKd5gx4oPXmBhTsZrWPEY/kkXpEPjITpexUpPsHQl7wMRO9
         5nfFGPm5f7oRoIa2TWNNxZ5EgzNTeIDHAuJjWFwLhqLWzx7zbg8z5lIApSXvpj1YjU03
         WjwuQOIktCTMmNRyAwDTZ3D0TEwO+sI2xM3D7EDEvFDtIrQ6xzr4AF3lD04dbquNDU1w
         Ffmp+Veb9pla8YC2jsqr0VjXD726mzxvBD7eQXe8Qcpa4SgPFDSfBcpSmvj7X/jKIqmC
         KTOZiTD826w6rVpRfYDPimDn/hB57YiPzaqIemKndTI4lj4Y0dZC6AKtVCEh1lW0VtSB
         xvbA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=Z4x6Sa5Wa1W3rpiLjgaavgksMivBnh4mWjuDtAy3jlo=;
        b=Cc9V1y4nlFb3+5KpNKUYaadzGvR5eFeVwsNCj9gQCe3X5z3Zv65SGmFToo7psULQ0n
         Pg27GolQna6TPsWOlZmkyf69KKoVMe5lxhT7mFA6GRcJtNbGi8vNhGEVDx0AkHQkr8Vq
         q7VUdjNgE5tN5DclaCLKtafs1wuz+nEuitcGvmGMeI74gJ+wrHaUhq6AL4wRaT1yaG9f
         E6F6PC3+ZmXvF31pYzVgSBUOiiF9A4eqUMFLuR5KXEsbjVtEu/I75iO1jX9u6uMZJkgw
         sKDClYg1SjrLRKcex5uA+u0DbMq07IArePu9crPyXq/mFtaYkbZusEKhol9Ke8F0P+AE
         oo6g==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=ppBlrpDo;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=zTJSvXDS;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o11.sgmail.github.com (o11.sgmail.github.com. [167.89.101.202])
        by mx.google.com with ESMTPS id 132si2015962itg.25.2017.10.19.14.50.09
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 14:50:09 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) client-ip=167.89.101.202;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=ppBlrpDo;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=zTJSvXDS;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=hScUABNHOleTI9/SFt42yXDL2i8=; b=ppBlrpDoou6NazUu
	NI49X6nVv672DwXXt3yAhEcu8QblMvvi56l2mtrcGuqUkHlCpwUhWVjzlbHacfIP
	U7QnUlzrr0PICF88CVzPaTv8EtdtRTSR+Z8YOWdgnpajFDmnC6MPED7cWilSHEa4
	TUe9zXVUiMbFrfjs2gV5V7gpoXc=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=hScUABNHOleTI9/SFt42yXDL2i8=; b=zTJSvXDSmXDuxiH5Bo
	SiLd09Vyq1cYcERLttDvQCVpRXs/KgcVsyUms8yudktyyXrT562ETWumZaO3UPK/
	dEsGZb7KbLNTh+pZjdi/N1vduydblkcy6FJs8SnHVC8jx2uQyWfNPs6USTk2GZMM
	+ixv2m2k3M7rKfpV0gPIhM7d8=
Received: by filter0976p1mdw1.sendgrid.net with SMTP id filter0976p1mdw1-18576-59E91E11-16
        2017-10-19 21:50:09.624842614 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0007p1iad1.sendgrid.net (SG) with ESMTP id 6Z2MSmaNSwyMjzfar9NeKA
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 21:50:09.568 +0000 (UTC)
Date: Thu, 19 Oct 2017 21:50:09 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f46.google.com ([209.85.218.46]:48366)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5IiL-001KRy-PQ
	for pawan@oss-india.net; Fri, 20 Oct 2017 03:21:08 +0530
Received: by mail-oi0-f46.google.com with SMTP id m198so17238177oig.5
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 14:50:32 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=WtyLo1qxJYQFKXavuWqEq9+XdklkUQ5mZq5G63qInrc=;
        b=d1FntnqtUdsQnLBCd9xROuE5R1Hjc8FwQltBzyAwt+i/uhI4nthuL+LU8V4nHDuNF6
         HnuMHxvowzEJMgMgYaccEMOuV8x/5D6lfPCZFZLEuSPrt7XtUY/Tl/SPxZOpPpYruIEa
         suTHq1W6cuC1lou8Q7uO4ayhR+xLr/gtWVqx8kJ1/rRvrsN8sopZZN2/WA2C6PAL7d4N
         3o7yIOzkdn/xFWmbcXGwDIXCHRqzJEU6K6xgX/cDViYfGpLJyNtCPL1j92ST3HQZRCV+
         v5UW/Rq0XdyrPbGLUrhm7n3enBHLD2VVHsGYWDD5ZFcwccsjNCEbUs4FZJhYZnKmy/B+
         SeAg==
X-Gm-Message-State: AMCzsaVv3JxI1xCARlOJTJDNGLjv/nTje+rHkgXuJBDMPgWASFvzDmyJ
	+KvzL/gN74Cr5CLvlvAm+bnm/7QYhb4Lrl+ywAIcWOTZNRFvC1k=
X-Received: by 10.202.71.86 with SMTP id u83mr1638319oia.16.1508449810816;
        Thu, 19 Oct 2017 14:50:10 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4355297ofa;
        Thu, 19 Oct 2017 14:50:10 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+Tte6IH0iOMqWpYIJTCi0Q9hfYlxj2FFzPcy4KZr23T+t7ELOh79N3jFb0NUZfYZLh/ADc4
X-Received: by 10.200.63.242 with SMTP id v47mr4488779qtk.29.1508449810203;
        Thu, 19 Oct 2017 14:50:10 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508449810; cv=none;
        d=google.com; s=arc-20160816;
        b=gXxGQhKjX2P70+Qh3nlgfY26R2F8a94d2OCX/gQbPikhQfvjMQLL3gFDUB/qEBkxg1
         3vauBzbAKmWpXYa0WmDI1gT2QV5uq4B/fVx5YTmIauCjUYXoNb0wP8NAfzXHDkwjFSSR
         nbB4QG0XvfXmYjSEv+u1DnVKlNdJGdVqnNrPH/KMO5gdpHeBq/r0dyUWfuBUi6EjkvCW
         rUTdmzG86zCx8cUe0rYIYv0H709HMl8IigN9IXGCInB2jovcxLKpk8oanL8tF7WDuERm
         Gs3BspO6hpk3uUECB3NMo2CzPr9jVjTNHZs7dIkP1h5kTyK6rGF10+2qnrSRS3vJEr+u
         6u+A==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=WtyLo1qxJYQFKXavuWqEq9+XdklkUQ5mZq5G63qInrc=;
        b=gIpTT+cf3xJxftpYXAoJkWHXSdqlMu42+VTcH9LR8xbaIUW4JMqqeMMca06LX0tj0+
         aY6yi/KL4qZKWOOtcCwpk3Tky4BBT79SQLpM1OyHZKgG7JxsFh+3TwiCK+VGKAgkUdcX
         vaBAkgNgYzM3uoCIuWWopLvFP12U5mmGd/jOtfsoZxRSmP7KQCFfcc0G4WSnxzAKRg0O
         n2+uthl872NrV1vQWsKSZR1/6fzZGoHimt0lxFcdLkFQzAb437GWLE8sW84nHcaA9Ro+
         3bwcHlCyc3lnSCvB+mujfwu51pcvMLk3A6MFk7NkEKJgTG/bv6wjR+tKitaFTSUIV3nl
         VCMA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=sYfw3PaL;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=E6z5yGDl;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o4.sgmail.github.com (o4.sgmail.github.com. [192.254.112.99])
        by mx.google.com with ESMTPS id k4si2249058qtj.2.2017.10.19.14.50.09
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 14:50:10 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) client-ip=192.254.112.99;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=sYfw3PaL;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=E6z5yGDl;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=QvyAr/evoLhu+q9tudOrhK2OOsM=; b=sYfw3PaLl03p4+Pd
	dFQweEHcLOvlaAQZ2ymVoOVT/xUSMHTDrDYmB5oF/WgRcbAgmr6NqAsEgGYtvrmr
	2daBZOI8Ilod9rDgjNgPvKnV/ZbaYcjbzDskmW8FycE3Ynrusff26wREVwNuCoGP
	diK11LRgTsbcGl3xj2zdXfo0pcA=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=QvyAr/evoLhu+q9tudOrhK2OOsM=; b=E6z5yGDl8u4N8iWdzE
	rLvLXbNVfSkLoPxiY7NdJmq4tveiWe9Y2TJx5TFsWgqFn7dP85gcBsyuTzaWoi9W
	Ux3lqN1JHMlcqOPQ9N3MHB/C0q91GrW1pAmkYchAGqL2OsL8NCA0beqzxtQ/buv3
	OBmdPvu/EaZDopDcaMiHY3Rv4=
Received: by filter0163p1iad2.sendgrid.net with SMTP id filter0163p1iad2-7964-59E91E11-25
        2017-10-19 21:50:09.559356311 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0025p1iad2.sendgrid.net (SG) with ESMTP id AgY_eIVeSGSBeJkgm6Ythg
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 21:50:09.425 +0000 (UTC)
Date: Thu, 19 Oct 2017 21:50:09 +0000 (UTC)

**Comment by rakhi2104** [comment]
Can I know why this is labelled Invalid ?? @texas2010

**Pull request closed without merging**
