### PR TITLE
Create Acceptance Criteria stub

### PR DESCRIPTION
**Pull request by physicsjoe**
First draft with links

### CODE REVIEW

**Comment by texas2010** [comment]
it seems you forget to add .md file name.

**Comment by physicsjoe** [comment]
@texas2010 Is that something that still needs fixing?
Point me in the right direction, if necessary

**Comment by texas2010** [comment]
@physicsjoe look at file. you could notice .md is missing.

**Comment by quiteBold** [comment]
Am I wrong, or should this file also reside in a folder named acceptance-criteria to make it visible on freecodecamp?

**Comment by physicsjoe** [comment]
@quiteBold I think that was my original goal

**Pull request merged**
