### PR TITLE
Added the description of Sorting Algorithms

### PR DESCRIPTION
**Pull request by anjalix**
This file was a stub. I want to make a contribution by adding this description.

### CODE REVIEW

**Comment by anjalix** [comment]
@texas2010 
Sir, I am new to this open source and I am unable to understand why my article got that 'duplicate' tag.
Could you please tell me what does this 'duplicate' tag mean and how can I rectify it.

**Comment by texas2010** [comment]
@anjalix, there is a reason to add the duplicate label. because there is more than one person write this article and make Pull requests for that article.

**Comment by texas2010** [comment]
in case if you want to see this. who did PR(pull request) it. https://github.com/freeCodeCamp/guides/pulls?q=is%3Apr+Sorting+is%3Aopen

**Comment by HKuz** [comment]
LGTM! Thanks for another contribution, @anjalix ! Because your PR was first, we reviewed it over the other duplicates 😄 I applied some formatting changes to make this article consistent with other ones we're seeing, and I simplified some of the list item sentences. Feel free to re-review and make any other changes in a new PR. 🔢 ➡️ 🔤

**Pull request merged**
