### PR TITLE
Improved Java articles

### PR DESCRIPTION
**Pull request by davcri**

### CODE REVIEW

**Comment by davcri** [comment]
In the following 3 days I probably will not have access to a PC and I cannot help with updating this PR.  
I'll come back soon with more desire to contribute to this wonderful project ;)

**Comment by systimotic** [comment]
@davcri Thanks for letting me know, see you soon!

**Comment by davcri** [comment]
Great 😄  
I'm currently making other changes

**Comment by davcri** [comment]
@systimotic new changes here: https://github.com/freeCodeCamp/guides/pull/990

**Pull request merged**
