### PR TITLE
Numerous contribution enhancements 💛

### PR DESCRIPTION
**Pull request by fvcproductions**
I've made numerous changes to the formatting and overall flow for contributions that I strongly believe will help with ensuring this project scales in a positive way.

The changes below are reflected in the `PULL_REQUEST_TEMPLATE` which provide checkboxes for the user to fill out to ensure new PRs follow a specific guideline.

I've updated the `README` to make it shorter so that it doesn't overwhelm the user and have moved most of the content to the `CONTRIBUTING` file.

I've added on an `ISSUE_TEMPLATE` as well.

Lastly, I modified the `LICENSE` to remove the `.md` extension as this is not required and removed the first line as it is unnecessary and merely copied `The 3-Clause BSD License` from [OpenSource.org](https://opensource.org/licenses/BSD-3-Clause).

Open to feedback and suggestions but I think we should try to get these changes in ASAP as more PRs trickle in.

---

## ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
  - Your PR should NOT be called `Update index.md` since it does not help the maintainer understand what has been changed.
  - For example, if you create a **Variables** article inside the **Python** directory, the pull request title should be **Python: add Variables article**.
  - Other examples are **Git: edit Git Commit article** or **PHP: create PHP section and add Data Structures article**
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/.github/CONTRIBUTING.md) so the Travis CI doesn't fail.
- [x] No plagiarized content or content that has been directly copied from another source.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@fvcproductions Thanks. I agree with the spirit of all of these changes, but this is way too many rules and they will discourage contributions. I recommend updating this to have as few rules as absolutely necessary. 

For example, "no plagiarism" is a realistic and important rule. "No grammar errors" is not a realistic or important rule. 

We are not looking for perfect pull requests here. We are looking for "good enough" pull requests.

See if you can get this down to the most important 3 important checkboxes, then remote the rest. The shorter and fewer steps, the more likely people will actually do these things.

**Comment by fvcproductions** [comment]
@QuincyLarson I definitely agree with making sure that creating a PR for this repo is accessible as possible.

I've shortened the PR template to 3 main bullet points so if you feel these make sense, I'll go ahead and merge. 😄

**Comment by fvcproductions** [comment]
Addresses https://github.com/freeCodeCamp/guides/issues/5344

**Comment by QuincyLarson** [comment]
@fvcproductions This looks solid. But why did you delete LICENSE.md and replace it with LICENSE?

**Comment by QuincyLarson** [comment]
@fvcproductions Your edits to README.md are dramatic. Many people spent a lot of time writing all of that.

Here's what I propose we do - remove your edits to README.md and open a separate pull request with them. Then we can have @hkuz and other contributors take a look at those edits. 

The optimal solution will probably be somewhere between our current README.md and the simplified version you're proposing.

**Comment by fvcproductions** [comment]
@QuincyLarson By default, GitHub doesn't use an extension but it doesn't change how it's shown regardless.

And I'll go ahead and remove the edits to the `README` so that other contributions can review those changes and agree which should be removed or not. 

To note, I did not remove any of the past changes - I just moved them to `CONTRIBUTING` where I felt they made more sense.

**Comment by fvcproductions** [comment]
@QuincyLarson I went ahead and reverted the `README` changes. Let me know what you think! 👍

**Comment by fvcproductions** [comment]
To note, I put `PULL_REQUEST_TEMPLATE`, `ISSUE_TEMPLATE` and `CONTRIBUTING` all under the `.github` folder as to [avoid clutter in root directory](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by fvcproductions** [comment]
I forgot to integrate changes made to `CONTRIBUTING` 3 days by a fellow reviewer ago so I'm going to make those changes and then merge. 😄

**Pull request merged**
