### PR TITLE
Added article for basic operators in Python

### PR DESCRIPTION
**Pull request by pragadheesh**

### CODE REVIEW

**Comment by texas2010** [comment]
Thank you for your pull request. Please read this [style guide](https://github.com/freeCodeCamp/guides#article-style-guide). I am closing this pull request for now. Please let me know if you have any questions.

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (122/100 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f45.google.com ([209.85.218.45]:48443)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5Jko-001brM-PV
	for pawan@oss-india.net; Fri, 20 Oct 2017 04:27:53 +0530
Received: by mail-oi0-f45.google.com with SMTP id m198so17454513oig.5
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 15:57:10 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=f+qjrnZXIUUeIrvfT2a7VeSCVL8E9d8A+mv4wNaQZps=;
        b=MyETjw0nlEUy7iiLoFYkjhx52cDvw3BYeDB+tml/B5VUT3v83B2qxNyKofauE2kKZM
         suHnbkkep38bGCAjifYs+LGvPdbeKV0CY7+1QNw4khNeA/QFU/Dlp/Mw+lBKun2GpV4x
         uzHYuS4+ZvQsatLTkji8XSjbydpz1o/ZL0h46g0QbdRGBU/qJDI4Dt/F0OFDbL9Hb2Lp
         GMTv4mzjWHR6kiOmvLQL2Vue44BgkNouM8Gf9BK6dy6DCLw7PkKWyGDzZW+bnO4NXTpE
         YenCNqHMXuUGa49ZgjrIQAyILvSX+sL/0tQRNDe7a8FqlHVUyMIimIyBsDDdcZrHsgvR
         wa6A==
X-Gm-Message-State: AMCzsaVlkKLTUD1+G/TBIMGfqnlRZlVXB0MtH0zYqb/oL0gyZLvyqTLF
	MPNgvaQqvBsemf/gg5AGq2jAW/WH6CL4Z/vUYzssrTYJaeZGh3g=
X-Received: by 10.157.4.197 with SMTP id 63mr2053970otm.346.1508453808059;
        Thu, 19 Oct 2017 15:56:48 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4405879ofa;
        Thu, 19 Oct 2017 15:56:47 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+TgYBqITNJ8wX/ptWJJN3LpsmAzIPdF3W5F0MGIYgVjvOlicek7ta9w7VsO8EAU9KItRdHR
X-Received: by 10.55.160.135 with SMTP id j129mr4052795qke.274.1508453807212;
        Thu, 19 Oct 2017 15:56:47 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508453807; cv=none;
        d=google.com; s=arc-20160816;
        b=iPfDV++0LFJbIXUDrGlGQ6MhSHTd7gI0gERdlkuY6GjfBxtXTPMnYBfxRRfyeSiBRE
         Ybn3IbA+NDlTz92pvphx21SxHMi0vQn6+Bg2yKpEUURPnomAuG8g8beOsSGglecjkHDC
         veqHJ0OMbFh00AhLAzwLkIWdGl0yI84/MzA5JT+roqOfdo6vYk/aXULRTwDJWX7raOXH
         sgoOTFRbuQD36niwZquKU+PiJB8BhBs4LdC84hB7nBwTXZEp0JzEel8JxHyUibxNGM01
         RhMDntf5cZk44U0GIeRwdi77K2Soqd4wvV2ighyscVQfYrQp0xwz/droDwjy1D2Myg2C
         XQCA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=f+qjrnZXIUUeIrvfT2a7VeSCVL8E9d8A+mv4wNaQZps=;
        b=Rlg7Ip27TbDBe37n9IO36EaM45S80Hpv1DCfY41ZuQbE5OJfThJtaaLgqFWqQSXBAw
         e2mJxYbMwKhoSm46JtgYoBysOt2eLDQLlrzXqzZErEBZqm7Y4Pa92lcot3xDNY/MyeYz
         Im/3dqujiWaHrbzcAJRVI2vXZqrpsjFV512PxVdy72eO5WfH2lc6rZJB354pWnZDe+3V
         k3YhtStpGn4kclNURj0I78Jhgx2gzyc4UXxk6Mpeb2RZXv28SMAxEVsrfpOGHQaGYPvJ
         vMK4U+LHPZY1Wc3TMlL1Ir3mnAnOWRY7U3aih3KyapqqngEUqqKhp4a4a+QyD7lmUyB4
         O4aA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=rHrZIE+f;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=PXGKNBYO;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o11.sgmail.github.com (o11.sgmail.github.com. [167.89.101.202])
        by mx.google.com with ESMTPS id e3si1534645qtc.337.2017.10.19.15.56.46
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 15:56:47 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) client-ip=167.89.101.202;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=rHrZIE+f;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=PXGKNBYO;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=WFd+Jhby1dwn6rATbGvQJCxpbSU=; b=rHrZIE+fGY2fZnWp
	8UNl0p6YzcurskaBKowlzNOfzLFiVqv+lIYcaSGM2MA16MRq3jUsQcZ0Mh11H79t
	E7D10gK3D0rtl9Fl9rbWThUF6/W0zDyrSnxXp8a7cyahiOUM/0/Crxfh1542RTmy
	mNs/2smVshORB2frSZsYyr8m1zA=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=WFd+Jhby1dwn6rATbGvQJCxpbSU=; b=PXGKNBYO6j/ZoTceFD
	JobQDUBvAGnNZ7q0EtYMwwhrxp8Yok1sKzrG/rW9NH9Khsztk8PzIlEmGdVu07sX
	6+zv1dhdoZ67lKVV/snllNUJGKjg5aI+B45siQzjeoWnNhKwl2cIfUtikuWtHO7z
	sxYMjTqJhrhBuK0QfT4M0EuBs=
Received: by filter0053p1iad2.sendgrid.net with SMTP id filter0053p1iad2-7070-59E92DAE-11
        2017-10-19 22:56:46.501356358 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0023p1iad2.sendgrid.net (SG) with ESMTP id AXyxEPuyT3SlwI6X_1TS_w
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 22:56:46.502 +0000 (UTC)
Date: Thu, 19 Oct 2017 22:56:46 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (123/100 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f49.google.com ([209.85.218.49]:56996)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1e5Jko-001brL-Nh
	for pawan@oss-india.net; Fri, 20 Oct 2017 04:27:54 +0530
Received: by mail-oi0-f49.google.com with SMTP id v9so17458612oif.13
        for <pawan@oss-india.net>; Thu, 19 Oct 2017 15:57:09 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=q++ELn8hrcuxcmGYne9CJUWuUrkpzd9kRc/UMRByxig=;
        b=Emo/IePKHKmojxLvhoFlF0qSamHPZe5zES1HiozW4MHM4H+afbNvCA0sJyPkBc/vDn
         RuQpeIOnEihvKF/rTskAnesTQfq9PXb/+Qun6GRQSVzVxr3bI7Ywj00yV2Y0hVVTeW6H
         NwMgD2JwaOUAGr680oKP9koKL8cR147/LPKnVxK/zBNH2iU/1dkxDNblDTjCwyHBXr2Z
         PP38VC0phafKSlqJr+zLco3JH/VkpBZF2SpI0gMHEbgNnSPP27Vle6iC+o66PHRr2okE
         Q/DLTr8F9+mmSzdeQfFxd/cWF3AoS/cBpkAWGAVVRXQVWVSA7j8Z5Mk6Ev9MyngdKB+U
         oTAg==
X-Gm-Message-State: AMCzsaXb9bh3MEC6Va5Rt7rFr2FhOifcYZmb9NDm01KT8BzWg1wP19hr
	iHiNGAfJfqs9C1f4gGPsVichn1kZGjaoe2jxZA5WGzahULT7Vhc=
X-Received: by 10.157.89.25 with SMTP id t25mr2099253oth.47.1508453807550;
        Thu, 19 Oct 2017 15:56:47 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.68.11 with SMTP id r11csp4405874ofa;
        Thu, 19 Oct 2017 15:56:46 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+TwoN905aHiieDhzoJpPqbTAmcKp8z9cbYWB2N4AnfEJqXflzyokzX68BrE/vQz9QPWU/7n
X-Received: by 10.55.209.155 with SMTP id o27mr4462137qkl.145.1508453806727;
        Thu, 19 Oct 2017 15:56:46 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1508453806; cv=none;
        d=google.com; s=arc-20160816;
        b=x9A6p/EuRWVuLUqOTE5C8VCbHgBkQNingHUkBpQ5lBj8/MQNXrOA3b5Rq6ZJ7+b8u0
         qF2RQQTz9NEw+krWCfjGj1m/oYCchrDzKmAvEXj9FZj91TwqwBIezSTIkc+ZxS9ogD/q
         qQ3QP3HfGeUiSEAOw9vVrpVx+/9w1L0YJ1EgFyIp0sC1hz1NogsnnsmTThwHkiIFCyVW
         bPMcKmBvvb5b6fTKMj1HiVM7OfRaboz9VAasx0ei76a90HB1RrURMVbrf9yZu523H05F
         qonyt9Ehrc/y//RUgUsRT5MsYXgKGcwHCwPtWtWEqALnXu1fs7dmJDAA0Nc+S2oY4tui
         EabA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=q++ELn8hrcuxcmGYne9CJUWuUrkpzd9kRc/UMRByxig=;
        b=YHz5odCmw2B7GA2fcEQuBSEj1+dkNJSmx7VQaQuOJPwT8qPipjKyZDCk03xRaht7hg
         TYEtMYbsNRKbRT8lcQX/24Ge7w4hnCd5/BFrsU0SD7wuSC0uDUaFoeiSvOgai7gYnBoa
         zal4pcO92o8/nGfEXCWYPhORFyB4AWzZFPtNAp1Mt9mTrUFna4zxxZrfKpp08dYYJK5m
         DHxyWtDE1aZ3E6t49o2MT3seXPWsCOZBqtVWWj9CNuEL7MFUdgErFikJEgs8nUYR+2PS
         1bnbef1NlAvzN2/yKuQNHT38l0/qjt9ni2Cq6XaCNwzsrto0oplHhVsqit6p+6h+7HE2
         l0xg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=QAnufbDu;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=ABBycXzN;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o1.sgmail.github.com (o1.sgmail.github.com. [192.254.114.176])
        by mx.google.com with ESMTPS id m34si2423466qtm.3.2017.10.19.15.56.46
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 19 Oct 2017 15:56:46 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) client-ip=192.254.114.176;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=QAnufbDu;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=ABBycXzN;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Fl3K02YyBpMzzBBk7IlpjP0EJ7o=; b=QAnufbDupCl5ZiPf
	+/7+h83wNzU3MVXG5AHIfuqA0j+/AadLHRx9knUaerjP/gzjD6nvwfqQECLfajlv
	xLX/Tq90r1n/Ak+j76wa4Flyt1fP6H5G/n2Rex495cZqbwFglMFmZnjmJcI1FImc
	Rwv7PZv7QPDAPO0axlqEePv5vvM=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=Fl3K02YyBpMzzBBk7IlpjP0EJ7o=; b=ABBycXzNIzVXwCndBf
	4bgUUh1gRrHx6zRnDYcH7jNNvocY/KefyPmqQLRsoIg4t/FR2Yu0tV+5a5rLPr9X
	AZk1ofoU0zmKyojWZVhMNlzr/hH2mQH9YzVnz/hoqEHly3q6TrPMxaTOeT8/8LTd
	o4lUGdvXfbEYyG8hwVfX0SB9s=
Received: by filter0197p1iad2.sendgrid.net with SMTP id filter0197p1iad2-29163-59E92DAE-2
        2017-10-19 22:56:46.024261251 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0011p1iad2.sendgrid.net (SG) with ESMTP id YHctgjRKS0u2EAbyedbgtA
	for <pawan.ossindia@gmail.com>; Thu, 19 Oct 2017 22:56:46.092 +0000 (UTC)
Date: Thu, 19 Oct 2017 22:56:46 +0000 (UTC)

**Comment by pragadheesh** [comment]
@texas2010 I have listed all the 7 basic operators, with an example for every operator in every category. Do you think the article is quite too long, and can cut out on examples for assignment operators or so?

Please let me know what kind of modifications are expected, so that I can update it accordingly.

**Pull request merged**
