### PR TITLE
Added article on Unconscious Bias

### PR DESCRIPTION
**Pull request by sage-godspeed**

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@sage-godspeed Awesome! This is a well-written explanation. Thanks for your contribution!

**Comment by QuincyLarson** [comment]
@sage-godspeed This article is plagiarized from: https://diversity.ucsf.edu/resources/unconscious-bias

Please read this: https://www.freecodecamp.org/academic-honesty

This is a one-time warning. If you get caught plagiarizing again we will have no choice but to ban you from the freeCodeCamp GitHub organization.

I am reverting this commit.

**Comment by sage-godspeed** [comment]
Good day Mr Quincy Larson
I am sorry for the trouble you have had to go with my article on
unconscious bias. I admit some part of my article was gotten from
https://diversity.ucsf.edu/resources/unconscious-bias
 I kind off forgot to cite or drop a link back to them them as with
standard procedure. I appeal to you to please give me another opportunity
to rectify it and retain my honour. I promise it won't happen again
Thank you for your consideration


PS: please in the guide to contributiong to freecodecamp guides be sure to
add a section addressing original content, citation and references and
plagiarism to avoid events like this from occurring in the nearest future.

**Comment by QuincyLarson** [comment]
@sage-godspeed Yes - I'm familiar with your many contributions.

Please create a new pull request adding proper citations to all of the articles you've contributed. Then we will merge this, and this will save everyone a lot of work removing your otherwise excellent articles.

We've added citation instructions here: https://github.com/freeCodeCamp/guides#attribution

**Pull request merged**
