### PR TITLE
Add polish translation of README.md

### PR DESCRIPTION
**Pull request by annakarpinska**
Dear fCC Guide team,
I allowed myself to create Polish translation of the README.md file from freeCodeCamp Guide repository. At the end of the translations/README.pl.md file I added "Translator's Information" section, translated to English below:

This translation is intended to facilitate the first contact with the freeCodeCamp guide to persons who communicate in the Polish language on daily basis. Currently, the freeCodeCamp guide articles (freeCodeCamp Guide) are created only in English and should be contributed in this language.

In the README file above:
- There are terms related to the computer science. Thoe terms were translated only in those place where they did not raise doubts
- GitHub interface and terminology have appeared. In most cases GitHub terms have not been translated, except for the term "branch", which in Polish is commonly used as "gałąź"
- The term "stub article", which literally translates to "kikut article", does not accurately reflect the meaning of this structure. For this reason, instead of the aforementioned phrase, the term "stem" (trzon) have been used.
 - In the "General writing tips" section, the original spelling of persons and phrases in English has been retained where these phrases explain how to write articles.

### CODE REVIEW

**Comment by HKuz** [comment]
@annakarpinska - this is awesome, thank you for taking the lead on creating a Polish version of the README. Translating Guide articles is on the Roadmap, but the project is so young we haven't formalized a process yet. 

@QuincyLarson, @Bouncey, @freeCodeCamp/moderators - requesting opinions on two things:
1) I like the sentence @annakarpinska adds ("Currently, the freeCodeCamp guide articles (freeCodeCamp Guide) are created only in English and should be contributed in this language.") - I think we should include something similar in a Translation section of the English README until we formalize the translation process.
2) I'm cool with merging this and keeping README translation files top-level in the repository - let me know thoughts, and how we want to name these files (this one is `README.pl.md` - I've seen the `README-pl.md` format in other repos)

**Comment by annakarpinska** [comment]
@HKuz - Thank You for feedback. Glad You like the general idea. I'm looking forward to see other comments and ready to make necessary changes if needed.

**Comment by Bouncey** [comment]
## LGTM 

Thanks @annakarpinska and @HKuz

**Comment by QuincyLarson** [comment]
@annakarpinska Awesome! Thank you for adding this Polish translation!

**Comment by QuincyLarson** [comment]
@annakarpinska That is an interesting idea.

We are going to focus on internationalization more heavily in 2018, and I think we could port some of these documents to other languages. We're also going to completely overhaul how the challenges are stored in the seed files to make it easier to have translations. So we can tackle this then. We'd welcome your help with it! :)

**Pull request merged**
