### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by audreylopes**
merge conflict resolved on li tag

### CODE REVIEW

**Comment by nsuchy** [comment]
Hey @audreylopes

I see this PR has had three commits however the files changed only shows a line was removed. In https://github.com/freeCodeCamp/guides/pull/7985/commits/9c37b01754cb96c9f75ef10ceea94193b64dc76f I can see you made certain changes. Could you help me understand what's going on here?

**Comment by nsuchy** [comment]
@audreylopes Any update on your progress? As well as the question I asked about this pull request?

**Comment by audreylopes** [comment]
Sorry for the late response to your comment @nsuchy ... What happened was that while solving the merge conflicts I realised someone else already made the changes that I was suggesting, so I ignored my own contribution. I completely forgot that I opened a pull request for this, so you can just ignore it ;)

**Comment by nsuchy** [comment]
So this pull request is no longer needed? I’ll close this for now. Add a comment if you’d like to reopen. Thanks for contributing :)

**Pull request closed without merging**
