### PR TITLE
Refactored a set of certificate articles

### PR DESCRIPTION
**Pull request by nsuchy**
This PR contains a refactor of several articles from the certifications section.

Notify: @isaacabrahamson

### CODE REVIEW

**Comment by IsaacAbrahamson** [comment]
@QuincyLarson, @freeCodeCamp/moderators, we are moving our wiki guide articles from the forum to the guide. Let's get this reviewed and merged so we can archive the old wiki guides on the forum.

**Comment by QuincyLarson** [comment]
@nsuchy Awesome! Well done. These all look like solid improvements. 

@IsaacAbrahamson I'm going to add you as a contributor to the Guide repo as well so you can merge these. Then you and @nsuchy can QA one another's progress on these :)

**Comment by IsaacAbrahamson** [comment]
@QuincyLarson Thanks! I believe you already made me a member, so I should have merge access (I've been reviewing and merging some guides already with the other reviewers).

So it is my understanding that all of the articles have been copied from the forum to the certificate section on the guide. Now we have to make formatting changes on the guide, and archive and add links to the old forum guides?

**Comment by QuincyLarson** [comment]
@IsaacAbrahamson Yes, that's correct. You have write access to this repo and can merge pull requests.

You don't don't need to link back to the forum. We are going to archive all those old forum versions of these articles. Going forward, the Guide will be the single official source of truth for hints on these challenges.

**Pull request merged**
