### PR TITLE
Add "Piecewise Function Graphs" article

### PR DESCRIPTION
**Pull request by codersc**

### CODE REVIEW

**Comment by Bouncey** [comment]
@codersc thanks for the article, we have removed the `articles` directory, can you please update your PR so that the article path would be `src/pages/mathematics/algebra/piecewise-functions-graphs/index.md`

Many thanks :+1:

**Comment by codersc** [comment]
@Bouncey I'm kinda still figuring out github :smiley:. Can I update the article path through the github UI, or do I need to do it with the command line?

**Comment by systimotic** [comment]
@codersc It seems like it's possible to do this with the GitHub UI: https://help.github.com/articles/moving-a-file-to-a-new-location/
Thanks for sticking with this!

**Comment by codersc** [comment]
@systimotic Thanks for the tip! It seems like the path should be updated now. If I did something wrong, let me know, and I can try to fix it.

**Comment by systimotic** [comment]
@codersc Thanks for that! Sadly, it didn't work, it still had merge conflicts 😞 Here's what I did to fix it:
```bash
# Before starting, make sure you're on the right branch (`patch-9` in this case)
# Undo renaming commit
git reset --hard HEAD~1
# Pull in latest changes
git pull --rebase upstream master
# Now I had to fix merge conflicts in my editor.
# It showed two parts, the stub and your content, and asked we which one I wanted to keep.
# I kept your changes and saved the file. Now I need to tell git to continue
git add .
git rebase --continue
# The conflict is resolved! Now we need to update the PR
git push -f origin patch-9
```

**Comment by codersc** [comment]
Thanks for letting me know how you fixed it @systimotic. I'll keep that in mind next time this issue comes up. :+1:

**Pull request merged**
