### PR TITLE
index.md

### PR DESCRIPTION
**Pull request by SHAKTISINGH2323**
This is the  README for a new guide in the  guide/src/pages on **Grunt** - a javascript task runner

### CODE REVIEW

**Comment by QuincyLarson** [comment]
This is off to a great start. The build failed and I noticed a few typos. Please get the build to pass and fix the typos. Then we’ll merge this.

**Comment by SHAKTISINGH2323** [comment]
okay , I will trying to fix them

**Comment by SHAKTISINGH2323** [comment]
okay , do my work finish ?

**Comment by SHAKTISINGH2323** [comment]
okay , how I do fix the typos ? or the build do itself

**Comment by SHAKTISINGH2323** [comment]
i fix the typos which i think need to be corrected but still build failed

**Comment by QuincyLarson** [comment]
@texas2010 @ChaituVR Travis is throwing this error:

```
Error: Error reading the frontmatter from "src/pages/bootstrap/bootstrap-card/index.md"
 at AnonymousObserver.listAllDirs.toArray.subscribe.err [as _onError] (/home/travis/build/freeCodeCamp/guides/bin/createNavData.js:56:15)
 at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:1836:12)
 at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:1772:14)
 at AnonymousObserver.tryCatcher (/home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:63:31)
 at AutoDetachObserverPrototype.error (/home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:5891:52)
 at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:1772:14)
 at InnerObserver.error (/home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:2501:59)
 at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:1772:14)
 at InnerObserver.tryCatcher (/home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:63:31)
 at AutoDetachObserverPrototype.error (/home/travis/build/freeCodeCamp/guides/node_modules/rx/dist/rx.js:5891:52)
```

Any idea how to fix this?

**Comment by texas2010** [comment]
i could see travis is failed because title is mistake.

**Comment by texas2010** [comment]
we already have grunt article.

**Comment by texas2010** [comment]
@SHAKTISINGH2323 Please untrack grunt article. we already have one. thanks!

**Comment by QuincyLarson** [comment]
@texas2010 Awesome - I'll look out for this kind of error on other pull requests, too. Thanks!

**Comment by SHAKTISINGH2323** [comment]
Okk

**Pull request closed without merging**
