### PR TITLE
Add R directory and index

### PR DESCRIPTION
**Pull request by AdrianMuntean**
**Description**

### CODE REVIEW

**Comment by Asjas** [comment]
Hey @AdrianMuntean 

I'd love to be able to merge your changes but it looks like there is an error with the Travis CI build. ⚠️

Once you resolve these issues, I will be able to review your PR and merge it. 😊

---

> Feel free to reference the [Article Style Guide](https://github.com/freeCodeCamp/guides#article-title) for this repo on formatting an article correctly so your Travis CI build passes. ✅
>
> Also, it's good practice on GitHub to write a brief description of your changes when creating a PR. 📝
Unfortunately your PR is failing the Travis Build. Please refer to our [Style Guide](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md#article-style-guide) on how a article should look.

**Comment by AdrianMuntean** [comment]
Hi @Asjas, this was closed and cannot be merged?

**Comment by Asjas** [comment]
@AdrianMuntean You need to fix your PR so that the Travis Build passes. I can't merge it if it fails.

I noticed your already deleted the branch that the PR was made from. My suggestion would be to create a new PR with your changes.

**Comment by AdrianMuntean** [comment]
Will do

**Pull request closed without merging**
