### PR TITLE
Create c-sharp

### PR DESCRIPTION
**Pull request by austinmscholl**
c-sharp folder

### CODE REVIEW

**Comment by erictleung** [comment]
@asprof34 thanks for starting the C# part of the guides! Can you fill out an `index.md` similar to how it is for [the C programming language](https://github.com/freeCodeCamp/guides/tree/master/src/pages/c). You don't need a filled out, but at least this much is sufficient.

```
---
title: C#
---
## C#

This is a stub. <a href='https://github.com/freecodecamp/guides/tree/master/src/pages/c-sharp/index.md' target='_blank' rel='nofollow'>Help our community expand it</a>.

<a href='https://github.com/freecodecamp/guides/blob/master/README.md' target='_blank' rel='nofollow'>This quick style guide will help ensure your pull request gets accepted</a>.

<!-- The article goes here, in GitHub-flavored Markdown. Feel free to add YouTube videos, images, and CodePen/JSBin embeds  -->

#### More Information:
<!-- Please add any articles you think might be helpful to read before writing the article -->
```

Thanks!

cc/ @Bouncey do you know if the `#` in the title will mess anything up?

**Comment by asprof34** [comment]
Where can I upload the csharp index.md file? For example, if I go to guides/src/pages and select "Create new file' it seems like the only reasonable place for me to upload it is the 'pages' directory.

**Comment by IsaacAbrahamson** [comment]
@erictleung, it looks like he submitted another pull request here:
https://github.com/freeCodeCamp/guides/pull/469

**Comment by texas2010** [comment]
I close this since he makes other PR and got the merge. cheer!

**Pull request closed without merging**
