### PR TITLE
Move OpenID Connect implicit flow article

### PR DESCRIPTION
**Pull request by systimotic**
It looks like this article accidentally ended up in the root directory instead of the `src/pages` directory through #2568 😅 
I couldn't find anything else to group it with, so I put it in the miscellaneous directory.

/cc @Asjas

---

#### ✅️ By submitting this PR, I have verified the following

- [x] Added descriptive name to PR
- [x] Reviewed necessary formatting guidelines in [`CONTRIBUTING.md`](https://github.com/freeCodeCamp/guides/blob/master/CONTRIBUTING.md).
- [x] No plagiarized, duplicate or repetitive  content that has been directly copied from another source.

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit 38a5f4b72b094ce6e304c7b5ac440fa3dd0599b9

https://deploy-preview-7929--guide.netlify.com

**Comment by BerkeleyTrue** [comment]
Deploy preview failed.

Built with commit 4c23efb1db554c8d6614d05fd2e7540386991b31

https://app.netlify.com/sites/guide/deploys/5a29bb20df9953198bd93b69

**Comment by Asjas** [comment]
Oh no :sweat_smile:. 
@systimotic Thanks for moving this. I failed to notice it was in root and not /src/pages.

**Comment by systimotic** [comment]
@Asjas No worries, I probably would have missed it too 😅 Thanks for merging!

**Pull request merged**
