### PR TITLE
Removed the articles directory

### PR DESCRIPTION
**Pull request by invinciblycool**
I have removed the articles directory and refactored `_createNavData.js` and `_normaliseArticles.js` accordingly.
Let me know if anything is incorrect.

### CODE REVIEW

**Comment by Bouncey** [comment]
@invinciblycool Did you run `_normaliseArticles.js` to test this? If you have, it doesn't seem that your changes have had the desired effect. The link to the article on GitHub still points to `.../src/pages/articles/...`.

**Comment by invinciblycool** [comment]
Apologies for not testing my code before opening a PR.
I don't know why the the main page is redirecting.
Any help?

**Comment by systimotic** [comment]
@invinciblycool I believe I remember that the `compontentWillMount` method of the `Layout` component in `layout.jsx` has this redirect set up. I also noticed `_createNavData` will need updates in the places where it says `.slice(9)` for the links in the nav to work. That's for after it starts showing up, though 😉

**Comment by Bouncey** [comment]
There is a redirect in Layout.jsx that pushes us to `/articles` if we land on the home page. We don't need it any more.

**Comment by invinciblycool** [comment]
I fixed the redirect to `/articles` but getting only the top navbar on the home page.
Also changing `.slice(9)` to `.slice(3)` is not working for me, after `topLevel = 'src/pages`.
Had a doubt that shouldn't the home page be redirected to `/pages` as all the pages are in there.

**Comment by Bouncey** [comment]
There is an index.md file in the articles dir that would need to be moved to the pages dir. The index.ns file in the pages dir can be removed. 

I don't understand what you mean about `.slice()`. 

The pages dir is only where we group all of our pages. Gatsby treats that as the home page or root of the website. 

Maybe it was unfair of me to ask for help on this as it now involves a restructure of a large section of the repo. I would be willing to take this off your hands if you would like.

**Comment by invinciblycool** [comment]
Sure, if that's how you feel.
:+1: 
I am sorry for not being able to fix the issue.

**Comment by Bouncey** [comment]
It's not as simple as I made it seem in the issue, which is entirely my fault. I'm sorry for taking up your time. 
The issue regarding the articles dir will essentially require a re-write of a large section of the repo

**Comment by systimotic** [comment]
Thanks for giving this a go anyway @invinciblycool!    ❤️    There's still plenty of other things to be done, we'd welcome your contributions.

**Pull request closed without merging**
