### PR TITLE
Added python articles for list methods.

### PR DESCRIPTION
**Pull request by invinciblycool**
Let me know if any corrections are needed.
Congratulations for guides.
:sparkles: :+1:

### CODE REVIEW

**Comment by invinciblycool** [comment]
I guess I will complete all the list functions.

**Comment by invinciblycool** [comment]
Added `index()`, `remove()` and `append()` methods to the PR.

**Comment by Bouncey** [comment]
Thanks @invinciblycool!

:sparkles: :sparkles: :sparkles: :sparkles:

**Comment by pragadheesh** [comment]
I have created a PR for sort() method. 
https://github.com/freeCodeCamp/guides/pull/832

**Comment by invinciblycool** [comment]
Thanks @pragadheesh for completing my job. Was busy with something else, so couldn't complete the articles.

**Pull request merged**
